// content/dyad.v1.js
// Static relation tables for the dyad reading (core/dyad.js), DOCTRINE §1.J.
//
// Data only — no derivation lives here. Every table is frozen and versioned
// per DOCTRINE §4 ("versioned, not edited"): a revision ships as dyad.v2.js
// rather than an in-place edit of this file.
//
// REGISTER (DOCTRINE §2 / §1.I register law). These strings describe the
// RELATION BETWEEN TWO COORDINATES as a named tradition files it. They are
// third person, declarative and materialist. They never score a pair, never
// rank one against another, never predict, never advise, and never claim
// that two people suit or fail to suit each other — the subject of every
// sentence is a branch, an element, a bracket or a number, never a person.
// `tests/dyad_content.test.js` runs the canonical BANNED_VOICE_REGISTER /
// second-person / diagnostic-framing / slur scans over every string here,
// plus a compatibility-claim scan this surface needs and the single-reading
// surfaces do not.
//
// REUSE. The wuxing cycles, the branch-relation families and the
// "recorded, not certified." qualifier are NOT redefined here — they are
// imported from the immutable content/concordance.v1.js registry, the same
// reuse pattern content/public.v1.js follows. The nine number meanings are
// likewise the existing registry (content/meanings.v2.js NUMEROLOGY_MEANINGS)
// consumed by core/dyad.js; this file authors only the combined-path clause
// that names the reduction, never a tenth copy of the number table.
//
// GRAMMAR DISCIPLINE (§1.J, mirroring the 144-catalog pins in
// tests/content_shape.test.js). Every `body` in this file is exactly one
// sentence: 10–22 words, a single terminal period, no `;` `?` `!`. Each
// table adds one further opener or verb rule, pinned per table below. The
// point is the deck's point — a later dyad.v2 updates the pins in the same
// PR, visibly, instead of drifting.

import {
  ELEMENTS,
  ELEMENT_SHENG,
  ELEMENT_KE,
  ANIMAL_RELATION_FAMILIES,
  CONCORDANCE_QUALIFIER,
} from './concordance.v1.js';

export {
  ELEMENTS,
  ELEMENT_SHENG,
  ELEMENT_KE,
  ANIMAL_RELATION_FAMILIES,
};

// The dyad makes no stronger claim than Concordance does, so it carries
// Concordance's qualifier rather than a second one worded more warmly.
export const DYAD_QUALIFIER = CONCORDANCE_QUALIFIER;

// Named tradition per axis, in the §1.E provenance posture: what a relation
// was read off, never what it is supposed to mean for anyone.
export const DYAD_SOURCES = Object.freeze({
  element: 'bazi · day-pillar heavenly stem, wuxing sheng and ke cycles',
  numerology: 'pythagorean numerology · life-path sum, nine-number system',
  cardPair: 'earthly branches · classical branch relations · catalog bracket arc',
});

// ── 1. Directed five-element relation between two day masters ───────────────
//
// Keyed `${from}_${to}` over all 25 ORDERED pairs of the five elements, so
// the A→B and B→A passages are two separate lookups rather than one passage
// read twice. There are no gaps and no fallback: for any ordered pair exactly
// one of the five kinds holds, and `tests/dyad_content.test.js` re-derives
// every entry's `kind` from ELEMENT_SHENG / ELEMENT_KE rather than trusting
// the table's own word.
//
// KIND → VERB register (pinned): sheng → "feeds" · sheng_by → "draws on" ·
// ke → "checks" · ke_by → "is checked by" · same → "meets". Every body opens
// with its `from` element and names its `to` element.
export const ELEMENT_RELATION_KINDS = Object.freeze({
  sheng: Object.freeze({ key: 'sheng', verb: 'feeds', label: 'generating' }),
  sheng_by: Object.freeze({ key: 'sheng_by', verb: 'draws on', label: 'generated by' }),
  ke: Object.freeze({ key: 'ke', verb: 'checks', label: 'controlling' }),
  ke_by: Object.freeze({ key: 'ke_by', verb: 'is checked by', label: 'controlled by' }),
  same: Object.freeze({ key: 'same', verb: 'meets', label: 'same phase' }),
});

export const ELEMENT_RELATIONS = Object.freeze({
  wood_wood: Object.freeze({
    from: 'wood', to: 'wood', kind: 'same',
    body: 'wood meets wood as a peer relation, two stocks of the same phase competing for the same ground.',
  }),
  wood_fire: Object.freeze({
    from: 'wood', to: 'fire', kind: 'sheng',
    body: 'wood feeds fire in the generating cycle, spending its own stock to raise the heat on the other side.',
  }),
  wood_earth: Object.freeze({
    from: 'wood', to: 'earth', kind: 'ke',
    body: 'wood checks earth in the controlling cycle, breaking open the ground on the other side with root pressure.',
  }),
  wood_metal: Object.freeze({
    from: 'wood', to: 'metal', kind: 'ke_by',
    body: 'wood is checked by metal in the controlling cycle, its growth cut back to the line the other works.',
  }),
  wood_water: Object.freeze({
    from: 'wood', to: 'water', kind: 'sheng_by',
    body: 'wood draws on water in the generating cycle, taking up the volume the other gives off.',
  }),

  fire_wood: Object.freeze({
    from: 'fire', to: 'wood', kind: 'sheng_by',
    body: 'fire draws on wood in the generating cycle, burning the stock the other spent seasons building.',
  }),
  fire_fire: Object.freeze({
    from: 'fire', to: 'fire', kind: 'same',
    body: 'fire meets fire as a peer relation, two heats of the same phase drawing on one supply.',
  }),
  fire_earth: Object.freeze({
    from: 'fire', to: 'earth', kind: 'sheng',
    body: 'fire feeds earth in the generating cycle, leaving behind the ash that thickens the ground on the other side.',
  }),
  fire_metal: Object.freeze({
    from: 'fire', to: 'metal', kind: 'ke',
    body: 'fire checks metal in the controlling cycle, softening the edge on the other side to the point of reshaping.',
  }),
  fire_water: Object.freeze({
    from: 'fire', to: 'water', kind: 'ke_by',
    body: 'fire is checked by water in the controlling cycle, its reach limited by the volume the other carries.',
  }),

  earth_wood: Object.freeze({
    from: 'earth', to: 'wood', kind: 'ke_by',
    body: 'earth is checked by wood in the controlling cycle, its ground opened by root pressure from the other side.',
  }),
  earth_fire: Object.freeze({
    from: 'earth', to: 'fire', kind: 'sheng_by',
    body: 'earth draws on fire in the generating cycle, thickening on the ash the other leaves behind.',
  }),
  earth_earth: Object.freeze({
    from: 'earth', to: 'earth', kind: 'same',
    body: 'earth meets earth as a peer relation, two masses of the same phase settling against one another.',
  }),
  earth_metal: Object.freeze({
    from: 'earth', to: 'metal', kind: 'sheng',
    body: 'earth feeds metal in the generating cycle, holding the ore long enough for the other to harden.',
  }),
  earth_water: Object.freeze({
    from: 'earth', to: 'water', kind: 'ke',
    body: 'earth checks water in the controlling cycle, banking the flow on the other side into a shape it can hold.',
  }),

  metal_wood: Object.freeze({
    from: 'metal', to: 'wood', kind: 'ke',
    body: 'metal checks wood in the controlling cycle, cutting the growth on the other side back to a worked line.',
  }),
  metal_fire: Object.freeze({
    from: 'metal', to: 'fire', kind: 'ke_by',
    body: 'metal is checked by fire in the controlling cycle, its edge softened to the point the other can reshape.',
  }),
  metal_earth: Object.freeze({
    from: 'metal', to: 'earth', kind: 'sheng_by',
    body: 'metal draws on earth in the generating cycle, hardening inside the ground the other holds.',
  }),
  metal_metal: Object.freeze({
    from: 'metal', to: 'metal', kind: 'same',
    body: 'metal meets metal as a peer relation, two edges of the same phase tested against one another.',
  }),
  metal_water: Object.freeze({
    from: 'metal', to: 'water', kind: 'sheng',
    body: 'metal feeds water in the generating cycle, condensing on its own cold face to release the other.',
  }),

  water_wood: Object.freeze({
    from: 'water', to: 'wood', kind: 'sheng',
    body: 'water feeds wood in the generating cycle, giving up volume so the other can put on growth.',
  }),
  water_fire: Object.freeze({
    from: 'water', to: 'fire', kind: 'ke',
    body: 'water checks fire in the controlling cycle, putting a limit on how far the heat opposite it travels.',
  }),
  water_earth: Object.freeze({
    from: 'water', to: 'earth', kind: 'ke_by',
    body: 'water is checked by earth in the controlling cycle, its flow banked into whatever shape the other holds.',
  }),
  water_metal: Object.freeze({
    from: 'water', to: 'metal', kind: 'sheng_by',
    body: 'water draws on metal in the generating cycle, collecting from the cold face the other presents.',
  }),
  water_water: Object.freeze({
    from: 'water', to: 'water', kind: 'same',
    body: 'water meets water as a peer relation, two volumes of the same phase joining into one body.',
  }),
});

// ── 2. Combined life path ───────────────────────────────────────────────────
//
// The two life paths are summed and reduced by the §1.B v0.54 nine-number
// rule, so the domain is exactly 1..9 (1+1 = 2 and 1+9 = 10 → 1 both land
// inside it). The NUMBER itself is not re-authored here: core/dyad.js reads
// its register and theme from the existing NUMEROLOGY_MEANINGS registry.
// What this table authors is the clause that names the REDUCTION — the one
// thing the single-sheet registry has no entry for, because a single sheet
// never combines two paths.
//
// Opener register (pinned): every body opens "the combined path reduces to
// <n>," and names that value's registered theme word.
export const COMBINED_PATH_NOTES = Object.freeze({
  1: Object.freeze({
    value: 1, theme: 'initiative',
    body: 'the combined path reduces to 1, the initiative register, which the tradition reads as starting a sequence rather than joining one.',
  }),
  2: Object.freeze({
    value: 2, theme: 'cooperation',
    body: 'the combined path reduces to 2, the cooperation register, which the tradition reads as attention split between two positions.',
  }),
  3: Object.freeze({
    value: 3, theme: 'expression',
    body: 'the combined path reduces to 3, the expression register, which the tradition reads as output put into circulation rather than kept.',
  }),
  4: Object.freeze({
    value: 4, theme: 'structure',
    body: 'the combined path reduces to 4, the structure register, which the tradition reads as work that builds a frame and keeps it.',
  }),
  5: Object.freeze({
    value: 5, theme: 'change',
    body: 'the combined path reduces to 5, the change register, which the tradition reads as movement between arrangements rather than settling.',
  }),
  6: Object.freeze({
    value: 6, theme: 'care',
    body: 'the combined path reduces to 6, the care register, which the tradition reads as responsibility carried for something outside the self.',
  }),
  7: Object.freeze({
    value: 7, theme: 'analysis',
    body: 'the combined path reduces to 7, the analysis register, which the tradition reads as examination held apart from the thing examined.',
  }),
  8: Object.freeze({
    value: 8, theme: 'command',
    body: 'the combined path reduces to 8, the command register, which the tradition reads as material authority exercised over a working system.',
  }),
  9: Object.freeze({
    value: 9, theme: 'service',
    body: 'the combined path reduces to 9, the service register, which the tradition reads as work directed outward past the immediate circle.',
  }),
});

// ── 3. Card pair — the four-slot grammar, read across two cells ─────────────
//
// The catalog cell is driven by (sunSign, animal) and its written note by the
// life-path bracket. A PAIR of cells therefore has exactly two registers to
// read across, and this table authors both:
//
//   (a) animal ↔ animal — the year branches, through the SAME five named
//       branch families Concordance already uses. `unfiled` is the honest
//       sixth state per the §1.I register law: same-value and unsupported
//       pairs claim nothing, and say so.
//   (b) bracket ↔ bracket — the deck's own arrival → construction → command
//       arc (the arc tests/content_shape.test.js pins across the 144 cells),
//       read as an ORDERED pair so low_high and high_low are distinct.
//
// Nothing here reads a card's authored name/type/habit/note. The pair passage
// is assembled from these two registers alone, so no deck string is copied,
// recombined, or re-authored — the §4 carve-out file stays the only tracked
// home of card-content strings.

// Opener register (pinned): every body opens "the two year branches".
export const BRANCH_REGISTERS = Object.freeze({
  liuhe: Object.freeze({
    key: 'liuhe',
    body: 'the two year branches sit in a named liuhe pair, a combination the branch tables file as mutually binding.',
  }),
  chong: Object.freeze({
    key: 'chong',
    body: 'the two year branches sit six places apart, the opposition the branch tables record as a direct clash.',
  }),
  sanhe: Object.freeze({
    key: 'sanhe',
    body: 'the two year branches belong to one named three-branch group, filed as members of a single trine.',
  }),
  hai: Object.freeze({
    key: 'hai',
    body: 'the two year branches sit in a named harm pair, a relation the branch tables record without further comment.',
  }),
  xing: Object.freeze({
    key: 'xing',
    body: 'the two year branches fall inside a named punishment relation, cyclic or mutual depending on the group cited.',
  }),
  unfiled: Object.freeze({
    key: 'unfiled', label: 'unfiled', note: 'no named branch relation on file',
    body: 'the two year branches appear in no named relation in the branch tables, so nothing is filed for this pair.',
  }),
});

// The three brackets and their position in the deck's authored arc. Named
// here so the pair bodies below and the tests share one vocabulary.
export const BRACKET_ARC = Object.freeze({
  low: 'arrival',
  mid: 'construction',
  high: 'command',
});

// Opener register (pinned): a matched pair opens "both entries sit in the";
// a mixed pair opens "the first entry sits in the". Keys are ORDERED
// `${bracketA}_${bracketB}`, all nine present.
export const BRACKET_REGISTERS = Object.freeze({
  low_low: Object.freeze({
    a: 'low', b: 'low',
    body: 'both entries sit in the arrival bracket, so the pair reads as two onsets with no construction stage in between.',
  }),
  low_mid: Object.freeze({
    a: 'low', b: 'mid',
    body: 'the first entry sits in the arrival bracket and the second in construction, an onset filed beside work already underway.',
  }),
  low_high: Object.freeze({
    a: 'low', b: 'high',
    body: 'the first entry sits in the arrival bracket and the second in command, an onset filed beside a settled position.',
  }),
  mid_low: Object.freeze({
    a: 'mid', b: 'low',
    body: 'the first entry sits in the construction bracket and the second in arrival, work underway filed beside a fresh onset.',
  }),
  mid_mid: Object.freeze({
    a: 'mid', b: 'mid',
    body: 'both entries sit in the construction bracket, so the pair reads as two builds running on the same stage.',
  }),
  mid_high: Object.freeze({
    a: 'mid', b: 'high',
    body: 'the first entry sits in the construction bracket and the second in command, a build filed beneath a settled position.',
  }),
  high_low: Object.freeze({
    a: 'high', b: 'low',
    body: 'the first entry sits in the command bracket and the second in arrival, a settled position filed beside a fresh onset.',
  }),
  high_mid: Object.freeze({
    a: 'high', b: 'mid',
    body: 'the first entry sits in the command bracket and the second in construction, a settled position filed beside work underway.',
  }),
  high_high: Object.freeze({
    a: 'high', b: 'high',
    body: 'both entries sit in the command bracket, so the pair reads as two settled positions with no build stage shown.',
  }),
});
