// 8ball / core / countries.js
// Country/zone entries for rising-sign location capture.
// Each entry maps to one fixed UTC offset (standard time, not DST).
// Coordinates are geographic-center defaults sourced primarily from the CIA
// World Factbook geographic-coordinates field and Wikipedia infobox equivalents,
// rounded to one decimal place.
// One decimal is intentional: about +/-11 km of coordinate precision, enough
// for country-scale rising-sign sign resolution while staying honest about
// centroid imprecision.
// Multi-tz entries use practical region centroids, population-weighted where
// the zone boundary is political rather than a canonical geographic unit.
// v0.5.2: legacy stored profiles still carry these country/zone codes,
// but rising-sign resolution now maps them to representative IANA
// timezones before calling computeRising. That keeps the stored-profile
// path on the same deterministic codepath as fresh city profiles without
// eager-loading assets/cities.json.

export const COUNTRIES = [
  { code: 'AF',        name: 'afghanistan',                                 utcOffsetMinutes:  270, defaultLat:  33.0, defaultLng:   65.0 },
  { code: 'AX',        name: 'aland islands',                               utcOffsetMinutes:  120, defaultLat:  60.1, defaultLng:   19.9 },
  { code: 'AL',        name: 'albania',                                     utcOffsetMinutes:   60, defaultLat:  41.0, defaultLng:   20.0 },
  { code: 'DZ',        name: 'algeria',                                     utcOffsetMinutes:   60, defaultLat:  28.0, defaultLng:    3.0 },
  { code: 'AD',        name: 'andorra',                                     utcOffsetMinutes:   60, defaultLat:  42.5, defaultLng:    1.5 },
  { code: 'AO',        name: 'angola',                                      utcOffsetMinutes:   60, defaultLat: -12.5, defaultLng:   18.5 },
  { code: 'AI',        name: 'anguilla',                                    utcOffsetMinutes: -240, defaultLat:  18.3, defaultLng:  -63.2 },
  { code: 'AQ',        name: 'antarctica',                                  utcOffsetMinutes:  720, defaultLat: -90.0, defaultLng:    0.0 },
  { code: 'AG',        name: 'antigua and barbuda',                         utcOffsetMinutes: -240, defaultLat:  17.1, defaultLng:  -61.8 },
  { code: 'AR',        name: 'argentina',                                   utcOffsetMinutes: -180, defaultLat: -34.0, defaultLng:  -64.0 },
  { code: 'AM',        name: 'armenia',                                     utcOffsetMinutes:  240, defaultLat:  40.0, defaultLng:   45.0 },
  { code: 'AW',        name: 'aruba',                                       utcOffsetMinutes: -240, defaultLat:  12.5, defaultLng:  -70.0 },
  { code: 'AU-CT',     name: 'australia (central)',                         utcOffsetMinutes:  570, defaultLat: -30.0, defaultLng:  135.0 },
  { code: 'AU-E',      name: 'australia (eastern)',                         utcOffsetMinutes:  600, defaultLat: -33.5, defaultLng:  150.0 },
  { code: 'AU-WA',     name: 'australia (western)',                         utcOffsetMinutes:  480, defaultLat: -27.0, defaultLng:  121.0 },
  { code: 'AT',        name: 'austria',                                     utcOffsetMinutes:   60, defaultLat:  47.3, defaultLng:   13.3 },
  { code: 'AZ',        name: 'azerbaijan',                                  utcOffsetMinutes:  240, defaultLat:  40.5, defaultLng:   47.5 },
  { code: 'BS',        name: 'bahamas',                                     utcOffsetMinutes: -300, defaultLat:  24.3, defaultLng:  -76.0 },
  { code: 'BH',        name: 'bahrain',                                     utcOffsetMinutes:  180, defaultLat:  26.0, defaultLng:   50.6 },
  { code: 'BD',        name: 'bangladesh',                                  utcOffsetMinutes:  360, defaultLat:  24.0, defaultLng:   90.0 },
  { code: 'BB',        name: 'barbados',                                    utcOffsetMinutes: -240, defaultLat:  13.2, defaultLng:  -59.5 },
  { code: 'BY',        name: 'belarus',                                     utcOffsetMinutes:  180, defaultLat:  53.0, defaultLng:   28.0 },
  { code: 'BE',        name: 'belgium',                                     utcOffsetMinutes:   60, defaultLat:  50.8, defaultLng:    4.0 },
  { code: 'BZ',        name: 'belize',                                      utcOffsetMinutes: -360, defaultLat:  17.3, defaultLng:  -88.8 },
  { code: 'BJ',        name: 'benin',                                       utcOffsetMinutes:   60, defaultLat:   9.5, defaultLng:    2.3 },
  { code: 'BM',        name: 'bermuda',                                     utcOffsetMinutes: -240, defaultLat:  32.3, defaultLng:  -64.8 },
  { code: 'BT',        name: 'bhutan',                                      utcOffsetMinutes:  360, defaultLat:  27.5, defaultLng:   90.5 },
  { code: 'BO',        name: 'bolivia',                                     utcOffsetMinutes: -240, defaultLat: -17.0, defaultLng:  -65.0 },
  { code: 'BA',        name: 'bosnia and herzegovina',                      utcOffsetMinutes:   60, defaultLat:  44.0, defaultLng:   18.0 },
  { code: 'BW',        name: 'botswana',                                    utcOffsetMinutes:  120, defaultLat: -22.0, defaultLng:   24.0 },
  { code: 'BV',        name: 'bouvet island',                               utcOffsetMinutes:    0, defaultLat: -54.4, defaultLng:    3.4 },
  { code: 'BR-AC',     name: 'brazil (acre)',                               utcOffsetMinutes: -300, defaultLat:  -8.8, defaultLng:  -70.5 },
  { code: 'BR-BR',     name: 'brazil (brasilia)',                           utcOffsetMinutes: -180, defaultLat: -15.5, defaultLng:  -56.0 },
  { code: 'BR-FN',     name: 'brazil (fernando de noronha)',                utcOffsetMinutes: -120, defaultLat:  -3.9, defaultLng:  -32.4 },
  { code: 'IO',        name: 'british indian ocean territory',              utcOffsetMinutes:  360, defaultLat:  -6.0, defaultLng:   71.5 },
  { code: 'VG',        name: 'british virgin islands',                      utcOffsetMinutes: -240, defaultLat:  18.5, defaultLng:  -64.5 },
  { code: 'BN',        name: 'brunei',                                      utcOffsetMinutes:  480, defaultLat:   4.5, defaultLng:  114.7 },
  { code: 'BG',        name: 'bulgaria',                                    utcOffsetMinutes:  120, defaultLat:  43.0, defaultLng:   25.0 },
  { code: 'BF',        name: 'burkina faso',                                utcOffsetMinutes:    0, defaultLat:  13.0, defaultLng:   -2.0 },
  { code: 'BI',        name: 'burundi',                                     utcOffsetMinutes:  120, defaultLat:  -3.5, defaultLng:   30.0 },
  { code: 'KH',        name: 'cambodia',                                    utcOffsetMinutes:  420, defaultLat:  13.0, defaultLng:  105.0 },
  { code: 'CM',        name: 'cameroon',                                    utcOffsetMinutes:   60, defaultLat:   6.0, defaultLng:   12.0 },
  { code: 'CA-AT',     name: 'canada (atlantic)',                           utcOffsetMinutes: -240, defaultLat:  46.0, defaultLng:  -63.0 },
  { code: 'CA-C',      name: 'canada (central)',                            utcOffsetMinutes: -360, defaultLat:  50.0, defaultLng:  -97.0 },
  { code: 'CA-E',      name: 'canada (eastern)',                            utcOffsetMinutes: -300, defaultLat:  46.0, defaultLng:  -75.0 },
  { code: 'CA-M',      name: 'canada (mountain)',                           utcOffsetMinutes: -420, defaultLat:  53.5, defaultLng: -115.0 },
  { code: 'CA-NL',     name: 'canada (newfoundland)',                       utcOffsetMinutes: -210, defaultLat:  49.0, defaultLng:  -56.0 },
  { code: 'CA-P',      name: 'canada (pacific)',                            utcOffsetMinutes: -480, defaultLat:  50.0, defaultLng: -120.0 },
  { code: 'CV',        name: 'cape verde',                                  utcOffsetMinutes:  -60, defaultLat:  16.0, defaultLng:  -24.0 },
  { code: 'BQ',        name: 'caribbean nl',                                utcOffsetMinutes: -240, defaultLat:  12.2, defaultLng:  -68.3 },
  { code: 'KY',        name: 'cayman islands',                              utcOffsetMinutes: -300, defaultLat:  19.5, defaultLng:  -80.5 },
  { code: 'CF',        name: 'central african rep.',                        utcOffsetMinutes:   60, defaultLat:   7.0, defaultLng:   21.0 },
  { code: 'TD',        name: 'chad',                                        utcOffsetMinutes:   60, defaultLat:  15.0, defaultLng:   19.0 },
  { code: 'CL-C',      name: 'chile (continental)',                         utcOffsetMinutes: -240, defaultLat: -30.0, defaultLng:  -71.0 },
  { code: 'CL-EI',     name: 'chile (easter island)',                       utcOffsetMinutes: -360, defaultLat: -27.1, defaultLng: -109.4 },
  { code: 'CN',        name: 'china',                                       utcOffsetMinutes:  480, defaultLat:  35.0, defaultLng:  105.0 },
  { code: 'CX',        name: 'christmas island',                            utcOffsetMinutes:  420, defaultLat: -10.5, defaultLng:  105.7 },
  { code: 'CC',        name: 'cocos islands',                               utcOffsetMinutes:  390, defaultLat: -12.5, defaultLng:   96.8 },
  { code: 'CO',        name: 'colombia',                                    utcOffsetMinutes: -300, defaultLat:   4.0, defaultLng:  -72.0 },
  { code: 'KM',        name: 'comoros',                                     utcOffsetMinutes:  180, defaultLat: -12.2, defaultLng:   44.3 },
  { code: 'CK',        name: 'cook islands',                                utcOffsetMinutes: -600, defaultLat: -21.2, defaultLng: -159.8 },
  { code: 'CR',        name: 'costa rica',                                  utcOffsetMinutes: -360, defaultLat:  10.0, defaultLng:  -84.0 },
  { code: 'CI',        name: 'cote d\'ivoire',                              utcOffsetMinutes:    0, defaultLat:   8.0, defaultLng:   -5.0 },
  { code: 'HR',        name: 'croatia',                                     utcOffsetMinutes:   60, defaultLat:  45.2, defaultLng:   15.5 },
  { code: 'CU',        name: 'cuba',                                        utcOffsetMinutes: -300, defaultLat:  21.5, defaultLng:  -80.0 },
  { code: 'CW',        name: 'curacao',                                     utcOffsetMinutes: -240, defaultLat:  12.2, defaultLng:  -69.0 },
  { code: 'CY',        name: 'cyprus',                                      utcOffsetMinutes:  120, defaultLat:  35.0, defaultLng:   33.0 },
  { code: 'CZ',        name: 'czech republic',                              utcOffsetMinutes:   60, defaultLat:  49.8, defaultLng:   15.5 },
  { code: 'CD',        name: 'democratic republic of the congo',            utcOffsetMinutes:   60, defaultLat:   0.0, defaultLng:   25.0 },
  { code: 'DK',        name: 'denmark',                                     utcOffsetMinutes:   60, defaultLat:  56.0, defaultLng:   10.0 },
  { code: 'DJ',        name: 'djibouti',                                    utcOffsetMinutes:  180, defaultLat:  11.5, defaultLng:   43.0 },
  { code: 'DM',        name: 'dominica',                                    utcOffsetMinutes: -240, defaultLat:  15.4, defaultLng:  -61.3 },
  { code: 'DO',        name: 'dominican republic',                          utcOffsetMinutes: -240, defaultLat:  19.0, defaultLng:  -70.7 },
  { code: 'TL',        name: 'east timor',                                  utcOffsetMinutes:  540, defaultLat:  -8.8, defaultLng:  125.9 },
  { code: 'EC',        name: 'ecuador',                                     utcOffsetMinutes: -300, defaultLat:  -2.0, defaultLng:  -77.5 },
  { code: 'EG',        name: 'egypt',                                       utcOffsetMinutes:  120, defaultLat:  27.0, defaultLng:   30.0 },
  { code: 'SV',        name: 'el salvador',                                 utcOffsetMinutes: -360, defaultLat:  13.8, defaultLng:  -88.9 },
  { code: 'GQ',        name: 'equatorial guinea',                           utcOffsetMinutes:   60, defaultLat:   2.0, defaultLng:   10.0 },
  { code: 'ER',        name: 'eritrea',                                     utcOffsetMinutes:  180, defaultLat:  15.0, defaultLng:   39.0 },
  { code: 'EE',        name: 'estonia',                                     utcOffsetMinutes:  120, defaultLat:  59.0, defaultLng:   26.0 },
  { code: 'SZ',        name: 'eswatini (swaziland)',                        utcOffsetMinutes:  120, defaultLat: -26.5, defaultLng:   31.5 },
  { code: 'ET',        name: 'ethiopia',                                    utcOffsetMinutes:  180, defaultLat:   8.0, defaultLng:   38.0 },
  { code: 'FK',        name: 'falkland islands',                            utcOffsetMinutes: -180, defaultLat: -51.8, defaultLng:  -59.0 },
  { code: 'FO',        name: 'faroe islands',                               utcOffsetMinutes:    0, defaultLat:  62.0, defaultLng:   -7.0 },
  { code: 'FJ',        name: 'fiji',                                        utcOffsetMinutes:  720, defaultLat: -18.0, defaultLng:  175.0 },
  { code: 'FI',        name: 'finland',                                     utcOffsetMinutes:  120, defaultLat:  64.0, defaultLng:   26.0 },
  { code: 'FR',        name: 'france',                                      utcOffsetMinutes:   60, defaultLat:  46.0, defaultLng:    2.0 },
  { code: 'GF',        name: 'french guiana',                               utcOffsetMinutes: -180, defaultLat:   4.0, defaultLng:  -53.0 },
  { code: 'PF',        name: 'french polynesia',                            utcOffsetMinutes: -600, defaultLat: -15.0, defaultLng: -140.0 },
  { code: 'TF',        name: 'french s. terr.',                             utcOffsetMinutes:  300, defaultLat: -49.3, defaultLng:   69.6 },
  { code: 'GA',        name: 'gabon',                                       utcOffsetMinutes:   60, defaultLat:  -1.0, defaultLng:   11.8 },
  { code: 'GM',        name: 'gambia',                                      utcOffsetMinutes:    0, defaultLat:  13.5, defaultLng:  -16.6 },
  { code: 'GE',        name: 'georgia',                                     utcOffsetMinutes:  240, defaultLat:  42.0, defaultLng:   43.5 },
  { code: 'DE',        name: 'germany',                                     utcOffsetMinutes:   60, defaultLat:  51.0, defaultLng:    9.0 },
  { code: 'GH',        name: 'ghana',                                       utcOffsetMinutes:    0, defaultLat:   8.0, defaultLng:   -2.0 },
  { code: 'GI',        name: 'gibraltar',                                   utcOffsetMinutes:   60, defaultLat:  36.1, defaultLng:   -5.4 },
  { code: 'GR',        name: 'greece',                                      utcOffsetMinutes:  120, defaultLat:  39.0, defaultLng:   22.0 },
  { code: 'GL',        name: 'greenland',                                   utcOffsetMinutes: -120, defaultLat:  72.0, defaultLng:  -40.0 },
  { code: 'GD',        name: 'grenada',                                     utcOffsetMinutes: -240, defaultLat:  12.1, defaultLng:  -61.7 },
  { code: 'GP',        name: 'guadeloupe',                                  utcOffsetMinutes: -240, defaultLat:  16.3, defaultLng:  -61.6 },
  { code: 'GU',        name: 'guam',                                        utcOffsetMinutes:  600, defaultLat:  13.5, defaultLng:  144.8 },
  { code: 'GT',        name: 'guatemala',                                   utcOffsetMinutes: -360, defaultLat:  15.5, defaultLng:  -90.3 },
  { code: 'GG',        name: 'guernsey',                                    utcOffsetMinutes:    0, defaultLat:  49.5, defaultLng:   -2.6 },
  { code: 'GN',        name: 'guinea',                                      utcOffsetMinutes:    0, defaultLat:  11.0, defaultLng:  -10.0 },
  { code: 'GW',        name: 'guinea-bissau',                               utcOffsetMinutes:    0, defaultLat:  12.0, defaultLng:  -15.0 },
  { code: 'GY',        name: 'guyana',                                      utcOffsetMinutes: -240, defaultLat:   5.0, defaultLng:  -59.0 },
  { code: 'HT',        name: 'haiti',                                       utcOffsetMinutes: -300, defaultLat:  19.0, defaultLng:  -72.4 },
  { code: 'HM',        name: 'heard island and mcdonald islands',           utcOffsetMinutes:    0, defaultLat: -53.1, defaultLng:   72.5 },
  { code: 'HN',        name: 'honduras',                                    utcOffsetMinutes: -360, defaultLat:  15.0, defaultLng:  -86.5 },
  { code: 'HK',        name: 'hong kong',                                   utcOffsetMinutes:  480, defaultLat:  22.3, defaultLng:  114.2 },
  { code: 'HU',        name: 'hungary',                                     utcOffsetMinutes:   60, defaultLat:  47.0, defaultLng:   20.0 },
  { code: 'IS',        name: 'iceland',                                     utcOffsetMinutes:    0, defaultLat:  65.0, defaultLng:  -18.0 },
  { code: 'IN',        name: 'india',                                       utcOffsetMinutes:  330, defaultLat:  21.0, defaultLng:   78.0 },
  { code: 'ID-WIB',    name: 'indonesia (wib)',                             utcOffsetMinutes:  420, defaultLat:  -6.2, defaultLng:  106.8 },
  { code: 'ID-WIT',    name: 'indonesia (wit)',                             utcOffsetMinutes:  540, defaultLat:  -4.0, defaultLng:  136.0 },
  { code: 'ID-WITA',   name: 'indonesia (wita)',                            utcOffsetMinutes:  480, defaultLat:  -2.0, defaultLng:  119.0 },
  { code: 'IR',        name: 'iran',                                        utcOffsetMinutes:  210, defaultLat:  32.0, defaultLng:   53.0 },
  { code: 'IQ',        name: 'iraq',                                        utcOffsetMinutes:  180, defaultLat:  33.0, defaultLng:   44.0 },
  { code: 'IE',        name: 'ireland',                                     utcOffsetMinutes:    0, defaultLat:  53.0, defaultLng:   -8.0 },
  { code: 'IM',        name: 'isle of man',                                 utcOffsetMinutes:    0, defaultLat:  54.3, defaultLng:   -4.5 },
  { code: 'IL',        name: 'israel',                                      utcOffsetMinutes:  120, defaultLat:  31.5, defaultLng:   34.8 },
  { code: 'IT',        name: 'italy',                                       utcOffsetMinutes:   60, defaultLat:  42.8, defaultLng:   12.8 },
  { code: 'JM',        name: 'jamaica',                                     utcOffsetMinutes: -300, defaultLat:  18.3, defaultLng:  -77.5 },
  { code: 'JP',        name: 'japan',                                       utcOffsetMinutes:  540, defaultLat:  36.0, defaultLng:  138.0 },
  { code: 'JE',        name: 'jersey',                                      utcOffsetMinutes:    0, defaultLat:  49.3, defaultLng:   -2.2 },
  { code: 'JO',        name: 'jordan',                                      utcOffsetMinutes:  180, defaultLat:  31.0, defaultLng:   36.0 },
  { code: 'KZ-E',      name: 'kazakhstan (east)',                           utcOffsetMinutes:  360, defaultLat:  49.0, defaultLng:   75.0 },
  { code: 'KZ-W',      name: 'kazakhstan (west)',                           utcOffsetMinutes:  300, defaultLat:  47.0, defaultLng:   55.0 },
  { code: 'KE',        name: 'kenya',                                       utcOffsetMinutes:  180, defaultLat:   1.0, defaultLng:   38.0 },
  { code: 'KI',        name: 'kiribati',                                    utcOffsetMinutes:  720, defaultLat:   1.4, defaultLng:  173.0 },
  { code: 'XK',        name: 'kosovo',                                      utcOffsetMinutes:   60, defaultLat:  42.6, defaultLng:   21.0 },
  { code: 'KW',        name: 'kuwait',                                      utcOffsetMinutes:  180, defaultLat:  29.5, defaultLng:   45.8 },
  { code: 'KG',        name: 'kyrgyzstan',                                  utcOffsetMinutes:  360, defaultLat:  41.0, defaultLng:   75.0 },
  { code: 'LA',        name: 'laos',                                        utcOffsetMinutes:  420, defaultLat:  18.0, defaultLng:  105.0 },
  { code: 'LV',        name: 'latvia',                                      utcOffsetMinutes:  120, defaultLat:  57.0, defaultLng:   25.0 },
  { code: 'LB',        name: 'lebanon',                                     utcOffsetMinutes:  120, defaultLat:  33.8, defaultLng:   35.8 },
  { code: 'LS',        name: 'lesotho',                                     utcOffsetMinutes:  120, defaultLat: -29.5, defaultLng:   28.5 },
  { code: 'LR',        name: 'liberia',                                     utcOffsetMinutes:    0, defaultLat:   6.5, defaultLng:   -9.5 },
  { code: 'LY',        name: 'libya',                                       utcOffsetMinutes:  120, defaultLat:  25.0, defaultLng:   17.0 },
  { code: 'LI',        name: 'liechtenstein',                               utcOffsetMinutes:   60, defaultLat:  47.3, defaultLng:    9.5 },
  { code: 'LT',        name: 'lithuania',                                   utcOffsetMinutes:  120, defaultLat:  56.0, defaultLng:   24.0 },
  { code: 'LU',        name: 'luxembourg',                                  utcOffsetMinutes:   60, defaultLat:  49.8, defaultLng:    6.2 },
  { code: 'MO',        name: 'macau',                                       utcOffsetMinutes:  480, defaultLat:  22.2, defaultLng:  113.6 },
  { code: 'MG',        name: 'madagascar',                                  utcOffsetMinutes:  180, defaultLat: -20.0, defaultLng:   47.0 },
  { code: 'MW',        name: 'malawi',                                      utcOffsetMinutes:  120, defaultLat: -13.5, defaultLng:   34.0 },
  { code: 'MY',        name: 'malaysia',                                    utcOffsetMinutes:  480, defaultLat:   2.5, defaultLng:  112.5 },
  { code: 'MV',        name: 'maldives',                                    utcOffsetMinutes:  300, defaultLat:   3.3, defaultLng:   73.0 },
  { code: 'ML',        name: 'mali',                                        utcOffsetMinutes:    0, defaultLat:  17.0, defaultLng:   -4.0 },
  { code: 'MT',        name: 'malta',                                       utcOffsetMinutes:   60, defaultLat:  35.8, defaultLng:   14.6 },
  { code: 'MH',        name: 'marshall islands',                            utcOffsetMinutes:  720, defaultLat:   9.0, defaultLng:  168.0 },
  { code: 'MQ',        name: 'martinique',                                  utcOffsetMinutes: -240, defaultLat:  14.7, defaultLng:  -61.0 },
  { code: 'MR',        name: 'mauritania',                                  utcOffsetMinutes:    0, defaultLat:  20.0, defaultLng:  -12.0 },
  { code: 'MU',        name: 'mauritius',                                   utcOffsetMinutes:  240, defaultLat: -20.3, defaultLng:   57.6 },
  { code: 'YT',        name: 'mayotte',                                     utcOffsetMinutes:  180, defaultLat: -12.8, defaultLng:   45.2 },
  { code: 'MX-CT',     name: 'mexico (central)',                            utcOffsetMinutes: -360, defaultLat:  21.0, defaultLng: -101.0 },
  { code: 'MX-NW',     name: 'mexico (northwest)',                          utcOffsetMinutes: -480, defaultLat:  30.0, defaultLng: -115.0 },
  { code: 'MX-PA',     name: 'mexico (pacific)',                            utcOffsetMinutes: -420, defaultLat:  28.0, defaultLng: -110.0 },
  { code: 'FM',        name: 'micronesia',                                  utcOffsetMinutes:  600, defaultLat:   6.9, defaultLng:  158.3 },
  { code: 'MD',        name: 'moldova',                                     utcOffsetMinutes:  120, defaultLat:  47.0, defaultLng:   29.0 },
  { code: 'MC',        name: 'monaco',                                      utcOffsetMinutes:   60, defaultLat:  43.7, defaultLng:    7.4 },
  { code: 'MN-E',      name: 'mongolia (east)',                             utcOffsetMinutes:  480, defaultLat:  47.9, defaultLng:  106.9 },
  { code: 'MN-W',      name: 'mongolia (west)',                             utcOffsetMinutes:  420, defaultLat:  48.0, defaultLng:   92.0 },
  { code: 'ME',        name: 'montenegro',                                  utcOffsetMinutes:   60, defaultLat:  42.5, defaultLng:   19.3 },
  { code: 'MS',        name: 'montserrat',                                  utcOffsetMinutes: -240, defaultLat:  16.8, defaultLng:  -62.2 },
  { code: 'MA',        name: 'morocco',                                     utcOffsetMinutes:   60, defaultLat:  28.5, defaultLng:  -10.0 },
  { code: 'MZ',        name: 'mozambique',                                  utcOffsetMinutes:  120, defaultLat: -18.3, defaultLng:   35.0 },
  { code: 'MM',        name: 'myanmar (burma)',                             utcOffsetMinutes:  390, defaultLat:  22.0, defaultLng:   98.0 },
  { code: 'NA',        name: 'namibia',                                     utcOffsetMinutes:  120, defaultLat: -22.0, defaultLng:   17.0 },
  { code: 'NR',        name: 'nauru',                                       utcOffsetMinutes:  720, defaultLat:  -0.5, defaultLng:  166.9 },
  { code: 'NP',        name: 'nepal',                                       utcOffsetMinutes:  345, defaultLat:  28.0, defaultLng:   84.0 },
  { code: 'NL',        name: 'netherlands',                                 utcOffsetMinutes:   60, defaultLat:  52.5, defaultLng:    5.8 },
  { code: 'NC',        name: 'new caledonia',                               utcOffsetMinutes:  660, defaultLat: -21.5, defaultLng:  165.5 },
  { code: 'NZ',        name: 'new zealand',                                 utcOffsetMinutes:  720, defaultLat: -41.0, defaultLng:  174.0 },
  { code: 'NI',        name: 'nicaragua',                                   utcOffsetMinutes: -360, defaultLat:  13.0, defaultLng:  -85.0 },
  { code: 'NE',        name: 'niger',                                       utcOffsetMinutes:   60, defaultLat:  16.0, defaultLng:    8.0 },
  { code: 'NG',        name: 'nigeria',                                     utcOffsetMinutes:   60, defaultLat:  10.0, defaultLng:    8.0 },
  { code: 'NU',        name: 'niue',                                        utcOffsetMinutes: -660, defaultLat: -19.0, defaultLng: -169.9 },
  { code: 'NF',        name: 'norfolk island',                              utcOffsetMinutes:  660, defaultLat: -29.0, defaultLng:  168.0 },
  { code: 'KP',        name: 'north korea',                                 utcOffsetMinutes:  540, defaultLat:  40.0, defaultLng:  127.0 },
  { code: 'MK',        name: 'north macedonia',                             utcOffsetMinutes:   60, defaultLat:  41.8, defaultLng:   22.0 },
  { code: 'MP',        name: 'northern mariana islands',                    utcOffsetMinutes:  600, defaultLat:  15.2, defaultLng:  145.8 },
  { code: 'NO',        name: 'norway',                                      utcOffsetMinutes:   60, defaultLat:  62.0, defaultLng:   10.0 },
  { code: 'OM',        name: 'oman',                                        utcOffsetMinutes:  240, defaultLat:  21.0, defaultLng:   57.0 },
  { code: 'PK',        name: 'pakistan',                                    utcOffsetMinutes:  300, defaultLat:  30.0, defaultLng:   70.0 },
  { code: 'PW',        name: 'palau',                                       utcOffsetMinutes:  540, defaultLat:   7.5, defaultLng:  134.5 },
  { code: 'PS',        name: 'palestine',                                   utcOffsetMinutes:  120, defaultLat:  31.9, defaultLng:   35.2 },
  { code: 'PA',        name: 'panama',                                      utcOffsetMinutes: -300, defaultLat:   9.0, defaultLng:  -80.0 },
  { code: 'PG',        name: 'papua new guinea',                            utcOffsetMinutes:  600, defaultLat:  -6.0, defaultLng:  147.0 },
  { code: 'PY',        name: 'paraguay',                                    utcOffsetMinutes: -240, defaultLat: -23.0, defaultLng:  -58.0 },
  { code: 'PE',        name: 'peru',                                        utcOffsetMinutes: -300, defaultLat: -10.0, defaultLng:  -76.0 },
  { code: 'PH',        name: 'philippines',                                 utcOffsetMinutes:  480, defaultLat:  13.0, defaultLng:  122.0 },
  { code: 'PN',        name: 'pitcairn',                                    utcOffsetMinutes: -480, defaultLat: -25.1, defaultLng: -130.1 },
  { code: 'PL',        name: 'poland',                                      utcOffsetMinutes:   60, defaultLat:  52.0, defaultLng:   20.0 },
  { code: 'PT',        name: 'portugal',                                    utcOffsetMinutes:    0, defaultLat:  39.5, defaultLng:   -8.0 },
  { code: 'PR',        name: 'puerto rico',                                 utcOffsetMinutes: -240, defaultLat:  18.3, defaultLng:  -66.5 },
  { code: 'QA',        name: 'qatar',                                       utcOffsetMinutes:  180, defaultLat:  25.5, defaultLng:   51.3 },
  { code: 'CG',        name: 'republic of the congo',                       utcOffsetMinutes:   60, defaultLat:  -1.0, defaultLng:   15.0 },
  { code: 'RE',        name: 'reunion',                                     utcOffsetMinutes:  240, defaultLat: -21.1, defaultLng:   55.6 },
  { code: 'RO',        name: 'romania',                                     utcOffsetMinutes:  120, defaultLat:  46.0, defaultLng:   25.0 },
  { code: 'RU-IRK',    name: 'russia (irkutsk)',                            utcOffsetMinutes:  480, defaultLat:  56.0, defaultLng:  105.0 },
  { code: 'RU-KAL',    name: 'russia (kaliningrad)',                        utcOffsetMinutes:  120, defaultLat:  54.7, defaultLng:   21.0 },
  { code: 'RU-KAM',    name: 'russia (kamchatka)',                          utcOffsetMinutes:  720, defaultLat:  56.0, defaultLng:  160.0 },
  { code: 'RU-MSK',    name: 'russia (moscow)',                             utcOffsetMinutes:  180, defaultLat:  56.0, defaultLng:   38.0 },
  { code: 'RU-VLA',    name: 'russia (vladivostok)',                        utcOffsetMinutes:  600, defaultLat:  45.0, defaultLng:  135.0 },
  { code: 'RU-EKB',    name: 'russia (yekaterinburg)',                      utcOffsetMinutes:  300, defaultLat:  57.0, defaultLng:   61.0 },
  { code: 'RW',        name: 'rwanda',                                      utcOffsetMinutes:  120, defaultLat:  -2.0, defaultLng:   30.0 },
  { code: 'AS',        name: 'samoa (american)',                            utcOffsetMinutes: -660, defaultLat: -14.3, defaultLng: -170.0 },
  { code: 'WS',        name: 'samoa (western)',                             utcOffsetMinutes:  780, defaultLat: -13.6, defaultLng: -172.3 },
  { code: 'SM',        name: 'san marino',                                  utcOffsetMinutes:   60, defaultLat:  43.8, defaultLng:   12.4 },
  { code: 'ST',        name: 'sao tome and principe',                       utcOffsetMinutes:    0, defaultLat:   1.0, defaultLng:    7.0 },
  { code: 'SA',        name: 'saudi arabia',                                utcOffsetMinutes:  180, defaultLat:  25.0, defaultLng:   45.0 },
  { code: 'SN',        name: 'senegal',                                     utcOffsetMinutes:    0, defaultLat:  14.0, defaultLng:  -14.0 },
  { code: 'RS',        name: 'serbia',                                      utcOffsetMinutes:   60, defaultLat:  44.0, defaultLng:   21.0 },
  { code: 'SC',        name: 'seychelles',                                  utcOffsetMinutes:  240, defaultLat:  -4.6, defaultLng:   55.7 },
  { code: 'SL',        name: 'sierra leone',                                utcOffsetMinutes:    0, defaultLat:   8.5, defaultLng:  -11.5 },
  { code: 'SG',        name: 'singapore',                                   utcOffsetMinutes:  480, defaultLat:   1.4, defaultLng:  103.8 },
  { code: 'SK',        name: 'slovakia',                                    utcOffsetMinutes:   60, defaultLat:  48.7, defaultLng:   19.5 },
  { code: 'SI',        name: 'slovenia',                                    utcOffsetMinutes:   60, defaultLat:  46.1, defaultLng:   14.8 },
  { code: 'SB',        name: 'solomon islands',                             utcOffsetMinutes:  660, defaultLat:  -8.0, defaultLng:  159.0 },
  { code: 'SO',        name: 'somalia',                                     utcOffsetMinutes:  180, defaultLat:  10.0, defaultLng:   49.0 },
  { code: 'ZA',        name: 'south africa',                                utcOffsetMinutes:  120, defaultLat: -29.0, defaultLng:   24.0 },
  { code: 'GS',        name: 'south georgia and south sandwich islands',    utcOffsetMinutes: -120, defaultLat: -54.5, defaultLng:  -37.0 },
  { code: 'KR',        name: 'south korea',                                 utcOffsetMinutes:  540, defaultLat:  37.0, defaultLng:  127.5 },
  { code: 'SS',        name: 'south sudan',                                 utcOffsetMinutes:  120, defaultLat:   8.0, defaultLng:   30.0 },
  { code: 'ES',        name: 'spain',                                       utcOffsetMinutes:   60, defaultLat:  40.0, defaultLng:   -4.0 },
  { code: 'LK',        name: 'sri lanka',                                   utcOffsetMinutes:  330, defaultLat:   7.0, defaultLng:   81.0 },
  { code: 'BL',        name: 'st barthelemy',                               utcOffsetMinutes: -240, defaultLat:  17.9, defaultLng:  -62.8 },
  { code: 'SH',        name: 'st helena',                                   utcOffsetMinutes:    0, defaultLat: -15.9, defaultLng:   -5.7 },
  { code: 'KN',        name: 'st kitts and nevis',                          utcOffsetMinutes: -240, defaultLat:  17.3, defaultLng:  -62.8 },
  { code: 'LC',        name: 'st lucia',                                    utcOffsetMinutes: -240, defaultLat:  13.9, defaultLng:  -61.0 },
  { code: 'SX',        name: 'st maarten (dutch)',                          utcOffsetMinutes: -240, defaultLat:  18.1, defaultLng:  -63.1 },
  { code: 'MF',        name: 'st martin (french)',                          utcOffsetMinutes: -240, defaultLat:  18.1, defaultLng:  -63.9 },
  { code: 'PM',        name: 'st pierre and miquelon',                      utcOffsetMinutes: -180, defaultLat:  46.8, defaultLng:  -56.3 },
  { code: 'VC',        name: 'st vincent',                                  utcOffsetMinutes: -240, defaultLat:  13.3, defaultLng:  -61.2 },
  { code: 'SD',        name: 'sudan',                                       utcOffsetMinutes:  120, defaultLat:  15.0, defaultLng:   30.0 },
  { code: 'SR',        name: 'suriname',                                    utcOffsetMinutes: -180, defaultLat:   4.0, defaultLng:  -56.0 },
  { code: 'SJ',        name: 'svalbard and jan mayen',                      utcOffsetMinutes:   60, defaultLat:  78.0, defaultLng:   20.0 },
  { code: 'SE',        name: 'sweden',                                      utcOffsetMinutes:   60, defaultLat:  62.0, defaultLng:   15.0 },
  { code: 'CH',        name: 'switzerland',                                 utcOffsetMinutes:   60, defaultLat:  47.0, defaultLng:    8.0 },
  { code: 'SY',        name: 'syria',                                       utcOffsetMinutes:  180, defaultLat:  35.0, defaultLng:   38.0 },
  { code: 'TW',        name: 'taiwan',                                      utcOffsetMinutes:  480, defaultLat:  23.5, defaultLng:  121.0 },
  { code: 'TJ',        name: 'tajikistan',                                  utcOffsetMinutes:  300, defaultLat:  39.0, defaultLng:   71.0 },
  { code: 'TZ',        name: 'tanzania',                                    utcOffsetMinutes:  180, defaultLat:  -6.0, defaultLng:   35.0 },
  { code: 'TH',        name: 'thailand',                                    utcOffsetMinutes:  420, defaultLat:  15.0, defaultLng:  100.0 },
  { code: 'TG',        name: 'togo',                                        utcOffsetMinutes:    0, defaultLat:   8.0, defaultLng:    1.2 },
  { code: 'TK',        name: 'tokelau',                                     utcOffsetMinutes:  780, defaultLat:  -9.0, defaultLng: -172.0 },
  { code: 'TO',        name: 'tonga',                                       utcOffsetMinutes:  780, defaultLat: -20.0, defaultLng: -175.0 },
  { code: 'TT',        name: 'trinidad and tobago',                         utcOffsetMinutes: -240, defaultLat:  11.0, defaultLng:  -61.0 },
  { code: 'TN',        name: 'tunisia',                                     utcOffsetMinutes:   60, defaultLat:  34.0, defaultLng:    9.0 },
  { code: 'TR',        name: 'turkey',                                      utcOffsetMinutes:  180, defaultLat:  39.0, defaultLng:   35.0 },
  { code: 'TM',        name: 'turkmenistan',                                utcOffsetMinutes:  300, defaultLat:  40.0, defaultLng:   60.0 },
  { code: 'TC',        name: 'turks and caicos is',                         utcOffsetMinutes: -300, defaultLat:  21.8, defaultLng:  -71.6 },
  { code: 'TV',        name: 'tuvalu',                                      utcOffsetMinutes:  720, defaultLat:  -8.0, defaultLng:  178.0 },
  { code: 'VI',        name: 'u.s. virgin islands',                         utcOffsetMinutes: -240, defaultLat:  18.3, defaultLng:  -64.8 },
  { code: 'UG',        name: 'uganda',                                      utcOffsetMinutes:  180, defaultLat:   1.0, defaultLng:   32.0 },
  { code: 'UA',        name: 'ukraine',                                     utcOffsetMinutes:  180, defaultLat:  49.0, defaultLng:   32.0 },
  { code: 'AE',        name: 'united arab emirates',                        utcOffsetMinutes:  240, defaultLat:  24.0, defaultLng:   54.0 },
  { code: 'GB',        name: 'united kingdom',                              utcOffsetMinutes:    0, defaultLat:  54.0, defaultLng:   -2.0 },
  { code: 'US-AK',     name: 'united states (alaska)',                      utcOffsetMinutes: -540, defaultLat:  64.0, defaultLng: -150.0 },
  { code: 'US-C',      name: 'united states (central)',                     utcOffsetMinutes: -360, defaultLat:  35.0, defaultLng:  -90.0 },
  { code: 'US-E',      name: 'united states (eastern)',                     utcOffsetMinutes: -300, defaultLat:  38.0, defaultLng:  -77.0 },
  { code: 'US-HI',     name: 'united states (hawaii)',                      utcOffsetMinutes: -600, defaultLat:  20.8, defaultLng: -156.3 },
  { code: 'US-M',      name: 'united states (mountain)',                    utcOffsetMinutes: -420, defaultLat:  39.0, defaultLng: -106.0 },
  { code: 'US-P',      name: 'united states (pacific)',                     utcOffsetMinutes: -480, defaultLat:  36.5, defaultLng: -119.5 },
  { code: 'UY',        name: 'uruguay',                                     utcOffsetMinutes: -180, defaultLat: -33.0, defaultLng:  -56.0 },
  { code: 'UM',        name: 'us minor outlying islands',                   utcOffsetMinutes: -660, defaultLat:  28.2, defaultLng: -177.4 },
  { code: 'UZ',        name: 'uzbekistan',                                  utcOffsetMinutes:  300, defaultLat:  41.0, defaultLng:   64.0 },
  { code: 'VU',        name: 'vanuatu',                                     utcOffsetMinutes:  660, defaultLat: -16.0, defaultLng:  167.0 },
  { code: 'VA',        name: 'vatican',                                     utcOffsetMinutes:   60, defaultLat:  41.9, defaultLng:   12.5 },
  { code: 'VE',        name: 'venezuela',                                   utcOffsetMinutes: -240, defaultLat:   8.0, defaultLng:  -66.0 },
  { code: 'VN',        name: 'vietnam',                                     utcOffsetMinutes:  420, defaultLat:  16.0, defaultLng:  108.0 },
  { code: 'WF',        name: 'wallis and futuna',                           utcOffsetMinutes:  720, defaultLat: -13.3, defaultLng: -176.2 },
  { code: 'EH',        name: 'western sahara',                              utcOffsetMinutes:   60, defaultLat:  24.5, defaultLng:  -13.0 },
  { code: 'YE',        name: 'yemen',                                       utcOffsetMinutes:  180, defaultLat:  15.0, defaultLng:   48.0 },
  { code: 'ZM',        name: 'zambia',                                      utcOffsetMinutes:  120, defaultLat: -15.0, defaultLng:   30.0 },
  { code: 'ZW',        name: 'zimbabwe',                                    utcOffsetMinutes:  120, defaultLat: -20.0, defaultLng:   30.0 },
];

// Representative IANA timezone for every legacy country/zone code above.
// For alpha-2 countries, this follows the largest-city timezone already
// present in assets/cities.json; split legacy codes use their named region.
export const LEGACY_COUNTRY_TIMEZONES = {
  'AF': 'Asia/Kabul',
  'AX': 'Europe/Mariehamn',
  'AL': 'Europe/Tirane',
  'DZ': 'Africa/Algiers',
  'AD': 'Europe/Andorra',
  'AO': 'Africa/Luanda',
  'AI': 'America/Anguilla',
  'AQ': 'Antarctica/McMurdo',
  'AG': 'America/Antigua',
  'AR': 'America/Argentina/Buenos_Aires',
  'AM': 'Asia/Yerevan',
  'AW': 'America/Aruba',
  'AU-CT': 'Australia/Adelaide',
  'AU-E': 'Australia/Sydney',
  'AU-WA': 'Australia/Perth',
  'AT': 'Europe/Vienna',
  'AZ': 'Asia/Baku',
  'BS': 'America/Nassau',
  'BH': 'Asia/Bahrain',
  'BD': 'Asia/Dhaka',
  'BB': 'America/Barbados',
  'BY': 'Europe/Minsk',
  'BE': 'Europe/Brussels',
  'BZ': 'America/Belize',
  'BJ': 'Africa/Porto-Novo',
  'BM': 'Atlantic/Bermuda',
  'BT': 'Asia/Thimphu',
  'BO': 'America/La_Paz',
  'BA': 'Europe/Sarajevo',
  'BW': 'Africa/Gaborone',
  'BV': 'Etc/GMT',
  'BR-AC': 'America/Rio_Branco',
  'BR-BR': 'America/Sao_Paulo',
  'BR-FN': 'America/Noronha',
  'IO': 'Indian/Chagos',
  'VG': 'America/Tortola',
  'BN': 'Asia/Brunei',
  'BG': 'Europe/Sofia',
  'BF': 'Africa/Ouagadougou',
  'BI': 'Africa/Bujumbura',
  'KH': 'Asia/Phnom_Penh',
  'CM': 'Africa/Douala',
  'CA-AT': 'America/Halifax',
  'CA-C': 'America/Winnipeg',
  'CA-E': 'America/Toronto',
  'CA-M': 'America/Edmonton',
  'CA-NL': 'America/St_Johns',
  'CA-P': 'America/Vancouver',
  'CV': 'Atlantic/Cape_Verde',
  'BQ': 'America/Kralendijk',
  'KY': 'America/Cayman',
  'CF': 'Africa/Bangui',
  'TD': 'Africa/Ndjamena',
  'CL-C': 'America/Santiago',
  'CL-EI': 'Pacific/Easter',
  'CN': 'Asia/Shanghai',
  'CX': 'Indian/Christmas',
  'CC': 'Indian/Cocos',
  'CO': 'America/Bogota',
  'KM': 'Indian/Comoro',
  'CK': 'Pacific/Rarotonga',
  'CR': 'America/Costa_Rica',
  'CI': 'Africa/Abidjan',
  'HR': 'Europe/Zagreb',
  'CU': 'America/Havana',
  'CW': 'America/Curacao',
  'CY': 'Asia/Nicosia',
  'CZ': 'Europe/Prague',
  'CD': 'Africa/Kinshasa',
  'DK': 'Europe/Copenhagen',
  'DJ': 'Africa/Djibouti',
  'DM': 'America/Dominica',
  'DO': 'America/Santo_Domingo',
  'TL': 'Asia/Dili',
  'EC': 'America/Guayaquil',
  'EG': 'Africa/Cairo',
  'SV': 'America/El_Salvador',
  'GQ': 'Africa/Malabo',
  'ER': 'Africa/Asmara',
  'EE': 'Europe/Tallinn',
  'SZ': 'Africa/Mbabane',
  'ET': 'Africa/Addis_Ababa',
  'FK': 'Atlantic/Stanley',
  'FO': 'Atlantic/Faroe',
  'FJ': 'Pacific/Fiji',
  'FI': 'Europe/Helsinki',
  'FR': 'Europe/Paris',
  'GF': 'America/Cayenne',
  'PF': 'Pacific/Tahiti',
  'TF': 'Indian/Kerguelen',
  'GA': 'Africa/Libreville',
  'GM': 'Africa/Banjul',
  'GE': 'Asia/Tbilisi',
  'DE': 'Europe/Berlin',
  'GH': 'Africa/Accra',
  'GI': 'Europe/Gibraltar',
  'GR': 'Europe/Athens',
  'GL': 'America/Nuuk',
  'GD': 'America/Grenada',
  'GP': 'America/Guadeloupe',
  'GU': 'Pacific/Guam',
  'GT': 'America/Guatemala',
  'GG': 'Europe/Guernsey',
  'GN': 'Africa/Conakry',
  'GW': 'Africa/Bissau',
  'GY': 'America/Guyana',
  'HT': 'America/Port-au-Prince',
  'HM': 'Etc/GMT-5',
  'HN': 'America/Tegucigalpa',
  'HK': 'Asia/Hong_Kong',
  'HU': 'Europe/Budapest',
  'IS': 'Atlantic/Reykjavik',
  'IN': 'Asia/Kolkata',
  'ID-WIB': 'Asia/Jakarta',
  'ID-WIT': 'Asia/Jayapura',
  'ID-WITA': 'Asia/Makassar',
  'IR': 'Asia/Tehran',
  'IQ': 'Asia/Baghdad',
  'IE': 'Europe/Dublin',
  'IM': 'Europe/Isle_of_Man',
  'IL': 'Asia/Jerusalem',
  'IT': 'Europe/Rome',
  'JM': 'America/Jamaica',
  'JP': 'Asia/Tokyo',
  'JE': 'Europe/Jersey',
  'JO': 'Asia/Amman',
  'KZ-E': 'Asia/Almaty',
  'KZ-W': 'Asia/Aqtau',
  'KE': 'Africa/Nairobi',
  'KI': 'Pacific/Tarawa',
  'XK': 'Europe/Belgrade',
  'KW': 'Asia/Kuwait',
  'KG': 'Asia/Bishkek',
  'LA': 'Asia/Vientiane',
  'LV': 'Europe/Riga',
  'LB': 'Asia/Beirut',
  'LS': 'Africa/Maseru',
  'LR': 'Africa/Monrovia',
  'LY': 'Africa/Tripoli',
  'LI': 'Europe/Vaduz',
  'LT': 'Europe/Vilnius',
  'LU': 'Europe/Luxembourg',
  'MO': 'Asia/Macau',
  'MG': 'Indian/Antananarivo',
  'MW': 'Africa/Blantyre',
  'MY': 'Asia/Kuala_Lumpur',
  'MV': 'Indian/Maldives',
  'ML': 'Africa/Bamako',
  'MT': 'Europe/Malta',
  'MH': 'Pacific/Majuro',
  'MQ': 'America/Martinique',
  'MR': 'Africa/Nouakchott',
  'MU': 'Indian/Mauritius',
  'YT': 'Indian/Mayotte',
  'MX-CT': 'America/Mexico_City',
  'MX-NW': 'America/Tijuana',
  'MX-PA': 'America/Mazatlan',
  'FM': 'Pacific/Chuuk',
  'MD': 'Europe/Chisinau',
  'MC': 'Europe/Monaco',
  'MN-E': 'Asia/Ulaanbaatar',
  'MN-W': 'Asia/Hovd',
  'ME': 'Europe/Podgorica',
  'MS': 'America/Montserrat',
  'MA': 'Africa/Casablanca',
  'MZ': 'Africa/Maputo',
  'MM': 'Asia/Yangon',
  'NA': 'Africa/Windhoek',
  'NR': 'Pacific/Nauru',
  'NP': 'Asia/Kathmandu',
  'NL': 'Europe/Amsterdam',
  'NC': 'Pacific/Noumea',
  'NZ': 'Pacific/Auckland',
  'NI': 'America/Managua',
  'NE': 'Africa/Niamey',
  'NG': 'Africa/Lagos',
  'NU': 'Pacific/Niue',
  'NF': 'Pacific/Norfolk',
  'KP': 'Asia/Pyongyang',
  'MK': 'Europe/Skopje',
  'MP': 'Pacific/Saipan',
  'NO': 'Europe/Oslo',
  'OM': 'Asia/Muscat',
  'PK': 'Asia/Karachi',
  'PW': 'Pacific/Palau',
  'PS': 'Asia/Hebron',
  'PA': 'America/Panama',
  'PG': 'Pacific/Port_Moresby',
  'PY': 'America/Asuncion',
  'PE': 'America/Lima',
  'PH': 'Asia/Manila',
  'PN': 'Pacific/Pitcairn',
  'PL': 'Europe/Warsaw',
  'PT': 'Europe/Lisbon',
  'PR': 'America/Puerto_Rico',
  'QA': 'Asia/Qatar',
  'CG': 'Africa/Brazzaville',
  'RE': 'Indian/Reunion',
  'RO': 'Europe/Bucharest',
  'RU-IRK': 'Asia/Irkutsk',
  'RU-KAL': 'Europe/Kaliningrad',
  'RU-KAM': 'Asia/Kamchatka',
  'RU-MSK': 'Europe/Moscow',
  'RU-VLA': 'Asia/Vladivostok',
  'RU-EKB': 'Asia/Yekaterinburg',
  'RW': 'Africa/Kigali',
  'AS': 'Pacific/Pago_Pago',
  'WS': 'Pacific/Apia',
  'SM': 'Europe/San_Marino',
  'ST': 'Africa/Sao_Tome',
  'SA': 'Asia/Riyadh',
  'SN': 'Africa/Dakar',
  'RS': 'Europe/Belgrade',
  'SC': 'Indian/Mahe',
  'SL': 'Africa/Freetown',
  'SG': 'Asia/Singapore',
  'SK': 'Europe/Bratislava',
  'SI': 'Europe/Ljubljana',
  'SB': 'Pacific/Guadalcanal',
  'SO': 'Africa/Mogadishu',
  'ZA': 'Africa/Johannesburg',
  'GS': 'Atlantic/South_Georgia',
  'KR': 'Asia/Seoul',
  'SS': 'Africa/Juba',
  'ES': 'Europe/Madrid',
  'LK': 'Asia/Colombo',
  'BL': 'America/St_Barthelemy',
  'SH': 'Atlantic/St_Helena',
  'KN': 'America/St_Kitts',
  'LC': 'America/St_Lucia',
  'SX': 'America/Lower_Princes',
  'MF': 'America/Marigot',
  'PM': 'America/Miquelon',
  'VC': 'America/St_Vincent',
  'SD': 'Africa/Khartoum',
  'SR': 'America/Paramaribo',
  'SJ': 'Arctic/Longyearbyen',
  'SE': 'Europe/Stockholm',
  'CH': 'Europe/Zurich',
  'SY': 'Asia/Damascus',
  'TW': 'Asia/Taipei',
  'TJ': 'Asia/Dushanbe',
  'TZ': 'Africa/Dar_es_Salaam',
  'TH': 'Asia/Bangkok',
  'TG': 'Africa/Lome',
  'TK': 'Pacific/Fakaofo',
  'TO': 'Pacific/Tongatapu',
  'TT': 'America/Port_of_Spain',
  'TN': 'Africa/Tunis',
  'TR': 'Europe/Istanbul',
  'TM': 'Asia/Ashgabat',
  'TC': 'America/Grand_Turk',
  'TV': 'Pacific/Funafuti',
  'VI': 'America/St_Thomas',
  'UG': 'Africa/Kampala',
  'UA': 'Europe/Kyiv',
  'AE': 'Asia/Dubai',
  'GB': 'Europe/London',
  'US-AK': 'America/Anchorage',
  'US-C': 'America/Chicago',
  'US-E': 'America/New_York',
  'US-HI': 'Pacific/Honolulu',
  'US-M': 'America/Denver',
  'US-P': 'America/Los_Angeles',
  'UY': 'America/Montevideo',
  'UM': 'Pacific/Midway',
  'UZ': 'Asia/Tashkent',
  'VU': 'Pacific/Efate',
  'VA': 'Europe/Vatican',
  'VE': 'America/Caracas',
  'VN': 'Asia/Ho_Chi_Minh',
  'WF': 'Pacific/Wallis',
  'EH': 'Africa/El_Aaiun',
  'YE': 'Asia/Aden',
  'ZM': 'Africa/Lusaka',
  'ZW': 'Africa/Harare',
};

export function getCountryByCode(code) {
  return COUNTRIES.find(c => c.code === code);
}

export function getCountryTimeZoneByCode(code) {
  return LEGACY_COUNTRY_TIMEZONES[code];
}
