// 8ball / core / countries.js
// Country/zone entries for rising-sign location capture.
// Each entry maps to one fixed UTC offset (standard time, not DST).
// Coordinates are geographic-center defaults sourced primarily from the CIA
// World Factbook geographic-coordinates field and Wikipedia infobox equivalents,
// rounded to one decimal place.
// One decimal is intentional: about +/-11 km of coordinate precision, enough
// for country-scale rising-sign sign resolution while staying honest about
// centroid imprecision.
// Multi-tz entries use practical region centroids, population-weighted where
// the zone boundary is political rather than a canonical geographic unit.
// v0.5.2: legacy stored profiles still carry these country/zone codes,
// but rising-sign resolution now maps them to representative IANA
// timezones before calling computeRising. That keeps the stored-profile
// path on the same deterministic codepath as fresh city profiles without
// eager-loading assets/cities.json.
//
// Note on country centroids: the legacy defaultLat/defaultLng fields were
// removed from these rows (deep-clean, 2026-07-25; supersedes the #78
// annotate-and-keep decision by operator word). No production codepath ever
// read them. The test coverage they backed is carried forward verbatim:
// tests/country_centroids.fixture.json holds the per-code [lat, lng] pairs,
// and tests/countries.test.js pins validity, keyset parity against this
// COUNTRIES table, and the pre-v0.5.2 fixed-offset vs unified-IANA rising
// divergence from that fixture.

export const COUNTRIES = [
  { code: 'AF',        name: 'afghanistan',                                 utcOffsetMinutes:  270 },
  { code: 'AX',        name: 'aland islands',                               utcOffsetMinutes:  120 },
  { code: 'AL',        name: 'albania',                                     utcOffsetMinutes:   60 },
  { code: 'DZ',        name: 'algeria',                                     utcOffsetMinutes:   60 },
  { code: 'AD',        name: 'andorra',                                     utcOffsetMinutes:   60 },
  { code: 'AO',        name: 'angola',                                      utcOffsetMinutes:   60 },
  { code: 'AI',        name: 'anguilla',                                    utcOffsetMinutes: -240 },
  { code: 'AQ',        name: 'antarctica',                                  utcOffsetMinutes:  720 },
  { code: 'AG',        name: 'antigua and barbuda',                         utcOffsetMinutes: -240 },
  { code: 'AR',        name: 'argentina',                                   utcOffsetMinutes: -180 },
  { code: 'AM',        name: 'armenia',                                     utcOffsetMinutes:  240 },
  { code: 'AW',        name: 'aruba',                                       utcOffsetMinutes: -240 },
  { code: 'AU-CT',     name: 'australia (central)',                         utcOffsetMinutes:  570 },
  { code: 'AU-E',      name: 'australia (eastern)',                         utcOffsetMinutes:  600 },
  { code: 'AU-WA',     name: 'australia (western)',                         utcOffsetMinutes:  480 },
  { code: 'AT',        name: 'austria',                                     utcOffsetMinutes:   60 },
  { code: 'AZ',        name: 'azerbaijan',                                  utcOffsetMinutes:  240 },
  { code: 'BS',        name: 'bahamas',                                     utcOffsetMinutes: -300 },
  { code: 'BH',        name: 'bahrain',                                     utcOffsetMinutes:  180 },
  { code: 'BD',        name: 'bangladesh',                                  utcOffsetMinutes:  360 },
  { code: 'BB',        name: 'barbados',                                    utcOffsetMinutes: -240 },
  { code: 'BY',        name: 'belarus',                                     utcOffsetMinutes:  180 },
  { code: 'BE',        name: 'belgium',                                     utcOffsetMinutes:   60 },
  { code: 'BZ',        name: 'belize',                                      utcOffsetMinutes: -360 },
  { code: 'BJ',        name: 'benin',                                       utcOffsetMinutes:   60 },
  { code: 'BM',        name: 'bermuda',                                     utcOffsetMinutes: -240 },
  { code: 'BT',        name: 'bhutan',                                      utcOffsetMinutes:  360 },
  { code: 'BO',        name: 'bolivia',                                     utcOffsetMinutes: -240 },
  { code: 'BA',        name: 'bosnia and herzegovina',                      utcOffsetMinutes:   60 },
  { code: 'BW',        name: 'botswana',                                    utcOffsetMinutes:  120 },
  { code: 'BV',        name: 'bouvet island',                               utcOffsetMinutes:    0 },
  { code: 'BR-AC',     name: 'brazil (acre)',                               utcOffsetMinutes: -300 },
  { code: 'BR-BR',     name: 'brazil (brasilia)',                           utcOffsetMinutes: -180 },
  { code: 'BR-FN',     name: 'brazil (fernando de noronha)',                utcOffsetMinutes: -120 },
  { code: 'IO',        name: 'british indian ocean territory',              utcOffsetMinutes:  360 },
  { code: 'VG',        name: 'british virgin islands',                      utcOffsetMinutes: -240 },
  { code: 'BN',        name: 'brunei',                                      utcOffsetMinutes:  480 },
  { code: 'BG',        name: 'bulgaria',                                    utcOffsetMinutes:  120 },
  { code: 'BF',        name: 'burkina faso',                                utcOffsetMinutes:    0 },
  { code: 'BI',        name: 'burundi',                                     utcOffsetMinutes:  120 },
  { code: 'KH',        name: 'cambodia',                                    utcOffsetMinutes:  420 },
  { code: 'CM',        name: 'cameroon',                                    utcOffsetMinutes:   60 },
  { code: 'CA-AT',     name: 'canada (atlantic)',                           utcOffsetMinutes: -240 },
  { code: 'CA-C',      name: 'canada (central)',                            utcOffsetMinutes: -360 },
  { code: 'CA-E',      name: 'canada (eastern)',                            utcOffsetMinutes: -300 },
  { code: 'CA-M',      name: 'canada (mountain)',                           utcOffsetMinutes: -420 },
  { code: 'CA-NL',     name: 'canada (newfoundland)',                       utcOffsetMinutes: -210 },
  { code: 'CA-P',      name: 'canada (pacific)',                            utcOffsetMinutes: -480 },
  { code: 'CV',        name: 'cape verde',                                  utcOffsetMinutes:  -60 },
  { code: 'BQ',        name: 'caribbean nl',                                utcOffsetMinutes: -240 },
  { code: 'KY',        name: 'cayman islands',                              utcOffsetMinutes: -300 },
  { code: 'CF',        name: 'central african rep.',                        utcOffsetMinutes:   60 },
  { code: 'TD',        name: 'chad',                                        utcOffsetMinutes:   60 },
  { code: 'CL-C',      name: 'chile (continental)',                         utcOffsetMinutes: -240 },
  { code: 'CL-EI',     name: 'chile (easter island)',                       utcOffsetMinutes: -360 },
  { code: 'CN',        name: 'china',                                       utcOffsetMinutes:  480 },
  { code: 'CX',        name: 'christmas island',                            utcOffsetMinutes:  420 },
  { code: 'CC',        name: 'cocos islands',                               utcOffsetMinutes:  390 },
  { code: 'CO',        name: 'colombia',                                    utcOffsetMinutes: -300 },
  { code: 'KM',        name: 'comoros',                                     utcOffsetMinutes:  180 },
  { code: 'CK',        name: 'cook islands',                                utcOffsetMinutes: -600 },
  { code: 'CR',        name: 'costa rica',                                  utcOffsetMinutes: -360 },
  { code: 'CI',        name: 'cote d\'ivoire',                              utcOffsetMinutes:    0 },
  { code: 'HR',        name: 'croatia',                                     utcOffsetMinutes:   60 },
  { code: 'CU',        name: 'cuba',                                        utcOffsetMinutes: -300 },
  { code: 'CW',        name: 'curacao',                                     utcOffsetMinutes: -240 },
  { code: 'CY',        name: 'cyprus',                                      utcOffsetMinutes:  120 },
  { code: 'CZ',        name: 'czech republic',                              utcOffsetMinutes:   60 },
  { code: 'CD',        name: 'democratic republic of the congo',            utcOffsetMinutes:   60 },
  { code: 'DK',        name: 'denmark',                                     utcOffsetMinutes:   60 },
  { code: 'DJ',        name: 'djibouti',                                    utcOffsetMinutes:  180 },
  { code: 'DM',        name: 'dominica',                                    utcOffsetMinutes: -240 },
  { code: 'DO',        name: 'dominican republic',                          utcOffsetMinutes: -240 },
  { code: 'TL',        name: 'east timor',                                  utcOffsetMinutes:  540 },
  { code: 'EC',        name: 'ecuador',                                     utcOffsetMinutes: -300 },
  { code: 'EG',        name: 'egypt',                                       utcOffsetMinutes:  120 },
  { code: 'SV',        name: 'el salvador',                                 utcOffsetMinutes: -360 },
  { code: 'GQ',        name: 'equatorial guinea',                           utcOffsetMinutes:   60 },
  { code: 'ER',        name: 'eritrea',                                     utcOffsetMinutes:  180 },
  { code: 'EE',        name: 'estonia',                                     utcOffsetMinutes:  120 },
  { code: 'SZ',        name: 'eswatini (swaziland)',                        utcOffsetMinutes:  120 },
  { code: 'ET',        name: 'ethiopia',                                    utcOffsetMinutes:  180 },
  { code: 'FK',        name: 'falkland islands',                            utcOffsetMinutes: -180 },
  { code: 'FO',        name: 'faroe islands',                               utcOffsetMinutes:    0 },
  { code: 'FJ',        name: 'fiji',                                        utcOffsetMinutes:  720 },
  { code: 'FI',        name: 'finland',                                     utcOffsetMinutes:  120 },
  { code: 'FR',        name: 'france',                                      utcOffsetMinutes:   60 },
  { code: 'GF',        name: 'french guiana',                               utcOffsetMinutes: -180 },
  { code: 'PF',        name: 'french polynesia',                            utcOffsetMinutes: -600 },
  { code: 'TF',        name: 'french s. terr.',                             utcOffsetMinutes:  300 },
  { code: 'GA',        name: 'gabon',                                       utcOffsetMinutes:   60 },
  { code: 'GM',        name: 'gambia',                                      utcOffsetMinutes:    0 },
  { code: 'GE',        name: 'georgia',                                     utcOffsetMinutes:  240 },
  { code: 'DE',        name: 'germany',                                     utcOffsetMinutes:   60 },
  { code: 'GH',        name: 'ghana',                                       utcOffsetMinutes:    0 },
  { code: 'GI',        name: 'gibraltar',                                   utcOffsetMinutes:   60 },
  { code: 'GR',        name: 'greece',                                      utcOffsetMinutes:  120 },
  { code: 'GL',        name: 'greenland',                                   utcOffsetMinutes: -120 },
  { code: 'GD',        name: 'grenada',                                     utcOffsetMinutes: -240 },
  { code: 'GP',        name: 'guadeloupe',                                  utcOffsetMinutes: -240 },
  { code: 'GU',        name: 'guam',                                        utcOffsetMinutes:  600 },
  { code: 'GT',        name: 'guatemala',                                   utcOffsetMinutes: -360 },
  { code: 'GG',        name: 'guernsey',                                    utcOffsetMinutes:    0 },
  { code: 'GN',        name: 'guinea',                                      utcOffsetMinutes:    0 },
  { code: 'GW',        name: 'guinea-bissau',                               utcOffsetMinutes:    0 },
  { code: 'GY',        name: 'guyana',                                      utcOffsetMinutes: -240 },
  { code: 'HT',        name: 'haiti',                                       utcOffsetMinutes: -300 },
  { code: 'HM',        name: 'heard island and mcdonald islands',           utcOffsetMinutes:    0 },
  { code: 'HN',        name: 'honduras',                                    utcOffsetMinutes: -360 },
  { code: 'HK',        name: 'hong kong',                                   utcOffsetMinutes:  480 },
  { code: 'HU',        name: 'hungary',                                     utcOffsetMinutes:   60 },
  { code: 'IS',        name: 'iceland',                                     utcOffsetMinutes:    0 },
  { code: 'IN',        name: 'india',                                       utcOffsetMinutes:  330 },
  { code: 'ID-WIB',    name: 'indonesia (wib)',                             utcOffsetMinutes:  420 },
  { code: 'ID-WIT',    name: 'indonesia (wit)',                             utcOffsetMinutes:  540 },
  { code: 'ID-WITA',   name: 'indonesia (wita)',                            utcOffsetMinutes:  480 },
  { code: 'IR',        name: 'iran',                                        utcOffsetMinutes:  210 },
  { code: 'IQ',        name: 'iraq',                                        utcOffsetMinutes:  180 },
  { code: 'IE',        name: 'ireland',                                     utcOffsetMinutes:    0 },
  { code: 'IM',        name: 'isle of man',                                 utcOffsetMinutes:    0 },
  { code: 'IL',        name: 'israel',                                      utcOffsetMinutes:  120 },
  { code: 'IT',        name: 'italy',                                       utcOffsetMinutes:   60 },
  { code: 'JM',        name: 'jamaica',                                     utcOffsetMinutes: -300 },
  { code: 'JP',        name: 'japan',                                       utcOffsetMinutes:  540 },
  { code: 'JE',        name: 'jersey',                                      utcOffsetMinutes:    0 },
  { code: 'JO',        name: 'jordan',                                      utcOffsetMinutes:  180 },
  { code: 'KZ-E',      name: 'kazakhstan (east)',                           utcOffsetMinutes:  360 },
  { code: 'KZ-W',      name: 'kazakhstan (west)',                           utcOffsetMinutes:  300 },
  { code: 'KE',        name: 'kenya',                                       utcOffsetMinutes:  180 },
  { code: 'KI',        name: 'kiribati',                                    utcOffsetMinutes:  720 },
  { code: 'XK',        name: 'kosovo',                                      utcOffsetMinutes:   60 },
  { code: 'KW',        name: 'kuwait',                                      utcOffsetMinutes:  180 },
  { code: 'KG',        name: 'kyrgyzstan',                                  utcOffsetMinutes:  360 },
  { code: 'LA',        name: 'laos',                                        utcOffsetMinutes:  420 },
  { code: 'LV',        name: 'latvia',                                      utcOffsetMinutes:  120 },
  { code: 'LB',        name: 'lebanon',                                     utcOffsetMinutes:  120 },
  { code: 'LS',        name: 'lesotho',                                     utcOffsetMinutes:  120 },
  { code: 'LR',        name: 'liberia',                                     utcOffsetMinutes:    0 },
  { code: 'LY',        name: 'libya',                                       utcOffsetMinutes:  120 },
  { code: 'LI',        name: 'liechtenstein',                               utcOffsetMinutes:   60 },
  { code: 'LT',        name: 'lithuania',                                   utcOffsetMinutes:  120 },
  { code: 'LU',        name: 'luxembourg',                                  utcOffsetMinutes:   60 },
  { code: 'MO',        name: 'macau',                                       utcOffsetMinutes:  480 },
  { code: 'MG',        name: 'madagascar',                                  utcOffsetMinutes:  180 },
  { code: 'MW',        name: 'malawi',                                      utcOffsetMinutes:  120 },
  { code: 'MY',        name: 'malaysia',                                    utcOffsetMinutes:  480 },
  { code: 'MV',        name: 'maldives',                                    utcOffsetMinutes:  300 },
  { code: 'ML',        name: 'mali',                                        utcOffsetMinutes:    0 },
  { code: 'MT',        name: 'malta',                                       utcOffsetMinutes:   60 },
  { code: 'MH',        name: 'marshall islands',                            utcOffsetMinutes:  720 },
  { code: 'MQ',        name: 'martinique',                                  utcOffsetMinutes: -240 },
  { code: 'MR',        name: 'mauritania',                                  utcOffsetMinutes:    0 },
  { code: 'MU',        name: 'mauritius',                                   utcOffsetMinutes:  240 },
  { code: 'YT',        name: 'mayotte',                                     utcOffsetMinutes:  180 },
  { code: 'MX-CT',     name: 'mexico (central)',                            utcOffsetMinutes: -360 },
  { code: 'MX-NW',     name: 'mexico (northwest)',                          utcOffsetMinutes: -480 },
  { code: 'MX-PA',     name: 'mexico (pacific)',                            utcOffsetMinutes: -420 },
  { code: 'FM',        name: 'micronesia',                                  utcOffsetMinutes:  600 },
  { code: 'MD',        name: 'moldova',                                     utcOffsetMinutes:  120 },
  { code: 'MC',        name: 'monaco',                                      utcOffsetMinutes:   60 },
  { code: 'MN-E',      name: 'mongolia (east)',                             utcOffsetMinutes:  480 },
  { code: 'MN-W',      name: 'mongolia (west)',                             utcOffsetMinutes:  420 },
  { code: 'ME',        name: 'montenegro',                                  utcOffsetMinutes:   60 },
  { code: 'MS',        name: 'montserrat',                                  utcOffsetMinutes: -240 },
  { code: 'MA',        name: 'morocco',                                     utcOffsetMinutes:   60 },
  { code: 'MZ',        name: 'mozambique',                                  utcOffsetMinutes:  120 },
  { code: 'MM',        name: 'myanmar (burma)',                             utcOffsetMinutes:  390 },
  { code: 'NA',        name: 'namibia',                                     utcOffsetMinutes:  120 },
  { code: 'NR',        name: 'nauru',                                       utcOffsetMinutes:  720 },
  { code: 'NP',        name: 'nepal',                                       utcOffsetMinutes:  345 },
  { code: 'NL',        name: 'netherlands',                                 utcOffsetMinutes:   60 },
  { code: 'NC',        name: 'new caledonia',                               utcOffsetMinutes:  660 },
  { code: 'NZ',        name: 'new zealand',                                 utcOffsetMinutes:  720 },
  { code: 'NI',        name: 'nicaragua',                                   utcOffsetMinutes: -360 },
  { code: 'NE',        name: 'niger',                                       utcOffsetMinutes:   60 },
  { code: 'NG',        name: 'nigeria',                                     utcOffsetMinutes:   60 },
  { code: 'NU',        name: 'niue',                                        utcOffsetMinutes: -660 },
  { code: 'NF',        name: 'norfolk island',                              utcOffsetMinutes:  660 },
  { code: 'KP',        name: 'north korea',                                 utcOffsetMinutes:  540 },
  { code: 'MK',        name: 'north macedonia',                             utcOffsetMinutes:   60 },
  { code: 'MP',        name: 'northern mariana islands',                    utcOffsetMinutes:  600 },
  { code: 'NO',        name: 'norway',                                      utcOffsetMinutes:   60 },
  { code: 'OM',        name: 'oman',                                        utcOffsetMinutes:  240 },
  { code: 'PK',        name: 'pakistan',                                    utcOffsetMinutes:  300 },
  { code: 'PW',        name: 'palau',                                       utcOffsetMinutes:  540 },
  { code: 'PS',        name: 'palestine',                                   utcOffsetMinutes:  120 },
  { code: 'PA',        name: 'panama',                                      utcOffsetMinutes: -300 },
  { code: 'PG',        name: 'papua new guinea',                            utcOffsetMinutes:  600 },
  { code: 'PY',        name: 'paraguay',                                    utcOffsetMinutes: -240 },
  { code: 'PE',        name: 'peru',                                        utcOffsetMinutes: -300 },
  { code: 'PH',        name: 'philippines',                                 utcOffsetMinutes:  480 },
  { code: 'PN',        name: 'pitcairn',                                    utcOffsetMinutes: -480 },
  { code: 'PL',        name: 'poland',                                      utcOffsetMinutes:   60 },
  { code: 'PT',        name: 'portugal',                                    utcOffsetMinutes:    0 },
  { code: 'PR',        name: 'puerto rico',                                 utcOffsetMinutes: -240 },
  { code: 'QA',        name: 'qatar',                                       utcOffsetMinutes:  180 },
  { code: 'CG',        name: 'republic of the congo',                       utcOffsetMinutes:   60 },
  { code: 'RE',        name: 'reunion',                                     utcOffsetMinutes:  240 },
  { code: 'RO',        name: 'romania',                                     utcOffsetMinutes:  120 },
  { code: 'RU-IRK',    name: 'russia (irkutsk)',                            utcOffsetMinutes:  480 },
  { code: 'RU-KAL',    name: 'russia (kaliningrad)',                        utcOffsetMinutes:  120 },
  { code: 'RU-KAM',    name: 'russia (kamchatka)',                          utcOffsetMinutes:  720 },
  { code: 'RU-MSK',    name: 'russia (moscow)',                             utcOffsetMinutes:  180 },
  { code: 'RU-VLA',    name: 'russia (vladivostok)',                        utcOffsetMinutes:  600 },
  { code: 'RU-EKB',    name: 'russia (yekaterinburg)',                      utcOffsetMinutes:  300 },
  { code: 'RW',        name: 'rwanda',                                      utcOffsetMinutes:  120 },
  { code: 'AS',        name: 'samoa (american)',                            utcOffsetMinutes: -660 },
  { code: 'WS',        name: 'samoa (western)',                             utcOffsetMinutes:  780 },
  { code: 'SM',        name: 'san marino',                                  utcOffsetMinutes:   60 },
  { code: 'ST',        name: 'sao tome and principe',                       utcOffsetMinutes:    0 },
  { code: 'SA',        name: 'saudi arabia',                                utcOffsetMinutes:  180 },
  { code: 'SN',        name: 'senegal',                                     utcOffsetMinutes:    0 },
  { code: 'RS',        name: 'serbia',                                      utcOffsetMinutes:   60 },
  { code: 'SC',        name: 'seychelles',                                  utcOffsetMinutes:  240 },
  { code: 'SL',        name: 'sierra leone',                                utcOffsetMinutes:    0 },
  { code: 'SG',        name: 'singapore',                                   utcOffsetMinutes:  480 },
  { code: 'SK',        name: 'slovakia',                                    utcOffsetMinutes:   60 },
  { code: 'SI',        name: 'slovenia',                                    utcOffsetMinutes:   60 },
  { code: 'SB',        name: 'solomon islands',                             utcOffsetMinutes:  660 },
  { code: 'SO',        name: 'somalia',                                     utcOffsetMinutes:  180 },
  { code: 'ZA',        name: 'south africa',                                utcOffsetMinutes:  120 },
  { code: 'GS',        name: 'south georgia and south sandwich islands',    utcOffsetMinutes: -120 },
  { code: 'KR',        name: 'south korea',                                 utcOffsetMinutes:  540 },
  { code: 'SS',        name: 'south sudan',                                 utcOffsetMinutes:  120 },
  { code: 'ES',        name: 'spain',                                       utcOffsetMinutes:   60 },
  { code: 'LK',        name: 'sri lanka',                                   utcOffsetMinutes:  330 },
  { code: 'BL',        name: 'st barthelemy',                               utcOffsetMinutes: -240 },
  { code: 'SH',        name: 'st helena',                                   utcOffsetMinutes:    0 },
  { code: 'KN',        name: 'st kitts and nevis',                          utcOffsetMinutes: -240 },
  { code: 'LC',        name: 'st lucia',                                    utcOffsetMinutes: -240 },
  { code: 'SX',        name: 'st maarten (dutch)',                          utcOffsetMinutes: -240 },
  { code: 'MF',        name: 'st martin (french)',                          utcOffsetMinutes: -240 },
  { code: 'PM',        name: 'st pierre and miquelon',                      utcOffsetMinutes: -180 },
  { code: 'VC',        name: 'st vincent',                                  utcOffsetMinutes: -240 },
  { code: 'SD',        name: 'sudan',                                       utcOffsetMinutes:  120 },
  { code: 'SR',        name: 'suriname',                                    utcOffsetMinutes: -180 },
  { code: 'SJ',        name: 'svalbard and jan mayen',                      utcOffsetMinutes:   60 },
  { code: 'SE',        name: 'sweden',                                      utcOffsetMinutes:   60 },
  { code: 'CH',        name: 'switzerland',                                 utcOffsetMinutes:   60 },
  { code: 'SY',        name: 'syria',                                       utcOffsetMinutes:  180 },
  { code: 'TW',        name: 'taiwan',                                      utcOffsetMinutes:  480 },
  { code: 'TJ',        name: 'tajikistan',                                  utcOffsetMinutes:  300 },
  { code: 'TZ',        name: 'tanzania',                                    utcOffsetMinutes:  180 },
  { code: 'TH',        name: 'thailand',                                    utcOffsetMinutes:  420 },
  { code: 'TG',        name: 'togo',                                        utcOffsetMinutes:    0 },
  { code: 'TK',        name: 'tokelau',                                     utcOffsetMinutes:  780 },
  { code: 'TO',        name: 'tonga',                                       utcOffsetMinutes:  780 },
  { code: 'TT',        name: 'trinidad and tobago',                         utcOffsetMinutes: -240 },
  { code: 'TN',        name: 'tunisia',                                     utcOffsetMinutes:   60 },
  { code: 'TR',        name: 'turkey',                                      utcOffsetMinutes:  180 },
  { code: 'TM',        name: 'turkmenistan',                                utcOffsetMinutes:  300 },
  { code: 'TC',        name: 'turks and caicos is',                         utcOffsetMinutes: -300 },
  { code: 'TV',        name: 'tuvalu',                                      utcOffsetMinutes:  720 },
  { code: 'VI',        name: 'u.s. virgin islands',                         utcOffsetMinutes: -240 },
  { code: 'UG',        name: 'uganda',                                      utcOffsetMinutes:  180 },
  { code: 'UA',        name: 'ukraine',                                     utcOffsetMinutes:  180 },
  { code: 'AE',        name: 'united arab emirates',                        utcOffsetMinutes:  240 },
  { code: 'GB',        name: 'united kingdom',                              utcOffsetMinutes:    0 },
  { code: 'US-AK',     name: 'united states (alaska)',                      utcOffsetMinutes: -540 },
  { code: 'US-C',      name: 'united states (central)',                     utcOffsetMinutes: -360 },
  { code: 'US-E',      name: 'united states (eastern)',                     utcOffsetMinutes: -300 },
  { code: 'US-HI',     name: 'united states (hawaii)',                      utcOffsetMinutes: -600 },
  { code: 'US-M',      name: 'united states (mountain)',                    utcOffsetMinutes: -420 },
  { code: 'US-P',      name: 'united states (pacific)',                     utcOffsetMinutes: -480 },
  { code: 'UY',        name: 'uruguay',                                     utcOffsetMinutes: -180 },
  { code: 'UM',        name: 'us minor outlying islands',                   utcOffsetMinutes: -660 },
  { code: 'UZ',        name: 'uzbekistan',                                  utcOffsetMinutes:  300 },
  { code: 'VU',        name: 'vanuatu',                                     utcOffsetMinutes:  660 },
  { code: 'VA',        name: 'vatican',                                     utcOffsetMinutes:   60 },
  { code: 'VE',        name: 'venezuela',                                   utcOffsetMinutes: -240 },
  { code: 'VN',        name: 'vietnam',                                     utcOffsetMinutes:  420 },
  { code: 'WF',        name: 'wallis and futuna',                           utcOffsetMinutes:  720 },
  { code: 'EH',        name: 'western sahara',                              utcOffsetMinutes:   60 },
  { code: 'YE',        name: 'yemen',                                       utcOffsetMinutes:  180 },
  { code: 'ZM',        name: 'zambia',                                      utcOffsetMinutes:  120 },
  { code: 'ZW',        name: 'zimbabwe',                                    utcOffsetMinutes:  120 },
];

// Representative IANA timezone for every legacy country/zone code above.
// For alpha-2 countries, this follows the largest-city timezone already
// present in assets/cities.json; split legacy codes use their named region.
export const LEGACY_COUNTRY_TIMEZONES = {
  'AF': 'Asia/Kabul',
  'AX': 'Europe/Mariehamn',
  'AL': 'Europe/Tirane',
  'DZ': 'Africa/Algiers',
  'AD': 'Europe/Andorra',
  'AO': 'Africa/Luanda',
  'AI': 'America/Anguilla',
  'AQ': 'Antarctica/McMurdo',
  'AG': 'America/Antigua',
  'AR': 'America/Argentina/Buenos_Aires',
  'AM': 'Asia/Yerevan',
  'AW': 'America/Aruba',
  'AU-CT': 'Australia/Adelaide',
  'AU-E': 'Australia/Sydney',
  'AU-WA': 'Australia/Perth',
  'AT': 'Europe/Vienna',
  'AZ': 'Asia/Baku',
  'BS': 'America/Nassau',
  'BH': 'Asia/Bahrain',
  'BD': 'Asia/Dhaka',
  'BB': 'America/Barbados',
  'BY': 'Europe/Minsk',
  'BE': 'Europe/Brussels',
  'BZ': 'America/Belize',
  'BJ': 'Africa/Porto-Novo',
  'BM': 'Atlantic/Bermuda',
  'BT': 'Asia/Thimphu',
  'BO': 'America/La_Paz',
  'BA': 'Europe/Sarajevo',
  'BW': 'Africa/Gaborone',
  'BV': 'Etc/GMT',
  'BR-AC': 'America/Rio_Branco',
  'BR-BR': 'America/Sao_Paulo',
  'BR-FN': 'America/Noronha',
  'IO': 'Indian/Chagos',
  'VG': 'America/Tortola',
  'BN': 'Asia/Brunei',
  'BG': 'Europe/Sofia',
  'BF': 'Africa/Ouagadougou',
  'BI': 'Africa/Bujumbura',
  'KH': 'Asia/Phnom_Penh',
  'CM': 'Africa/Douala',
  'CA-AT': 'America/Halifax',
  'CA-C': 'America/Winnipeg',
  'CA-E': 'America/Toronto',
  'CA-M': 'America/Edmonton',
  'CA-NL': 'America/St_Johns',
  'CA-P': 'America/Vancouver',
  'CV': 'Atlantic/Cape_Verde',
  'BQ': 'America/Kralendijk',
  'KY': 'America/Cayman',
  'CF': 'Africa/Bangui',
  'TD': 'Africa/Ndjamena',
  'CL-C': 'America/Santiago',
  'CL-EI': 'Pacific/Easter',
  'CN': 'Asia/Shanghai',
  'CX': 'Indian/Christmas',
  'CC': 'Indian/Cocos',
  'CO': 'America/Bogota',
  'KM': 'Indian/Comoro',
  'CK': 'Pacific/Rarotonga',
  'CR': 'America/Costa_Rica',
  'CI': 'Africa/Abidjan',
  'HR': 'Europe/Zagreb',
  'CU': 'America/Havana',
  'CW': 'America/Curacao',
  'CY': 'Asia/Nicosia',
  'CZ': 'Europe/Prague',
  'CD': 'Africa/Kinshasa',
  'DK': 'Europe/Copenhagen',
  'DJ': 'Africa/Djibouti',
  'DM': 'America/Dominica',
  'DO': 'America/Santo_Domingo',
  'TL': 'Asia/Dili',
  'EC': 'America/Guayaquil',
  'EG': 'Africa/Cairo',
  'SV': 'America/El_Salvador',
  'GQ': 'Africa/Malabo',
  'ER': 'Africa/Asmara',
  'EE': 'Europe/Tallinn',
  'SZ': 'Africa/Mbabane',
  'ET': 'Africa/Addis_Ababa',
  'FK': 'Atlantic/Stanley',
  'FO': 'Atlantic/Faroe',
  'FJ': 'Pacific/Fiji',
  'FI': 'Europe/Helsinki',
  'FR': 'Europe/Paris',
  'GF': 'America/Cayenne',
  'PF': 'Pacific/Tahiti',
  'TF': 'Indian/Kerguelen',
  'GA': 'Africa/Libreville',
  'GM': 'Africa/Banjul',
  'GE': 'Asia/Tbilisi',
  'DE': 'Europe/Berlin',
  'GH': 'Africa/Accra',
  'GI': 'Europe/Gibraltar',
  'GR': 'Europe/Athens',
  'GL': 'America/Nuuk',
  'GD': 'America/Grenada',
  'GP': 'America/Guadeloupe',
  'GU': 'Pacific/Guam',
  'GT': 'America/Guatemala',
  'GG': 'Europe/Guernsey',
  'GN': 'Africa/Conakry',
  'GW': 'Africa/Bissau',
  'GY': 'America/Guyana',
  'HT': 'America/Port-au-Prince',
  'HM': 'Etc/GMT-5',
  'HN': 'America/Tegucigalpa',
  'HK': 'Asia/Hong_Kong',
  'HU': 'Europe/Budapest',
  'IS': 'Atlantic/Reykjavik',
  'IN': 'Asia/Kolkata',
  'ID-WIB': 'Asia/Jakarta',
  'ID-WIT': 'Asia/Jayapura',
  'ID-WITA': 'Asia/Makassar',
  'IR': 'Asia/Tehran',
  'IQ': 'Asia/Baghdad',
  'IE': 'Europe/Dublin',
  'IM': 'Europe/Isle_of_Man',
  'IL': 'Asia/Jerusalem',
  'IT': 'Europe/Rome',
  'JM': 'America/Jamaica',
  'JP': 'Asia/Tokyo',
  'JE': 'Europe/Jersey',
  'JO': 'Asia/Amman',
  'KZ-E': 'Asia/Almaty',
  'KZ-W': 'Asia/Aqtau',
  'KE': 'Africa/Nairobi',
  'KI': 'Pacific/Tarawa',
  'XK': 'Europe/Belgrade',
  'KW': 'Asia/Kuwait',
  'KG': 'Asia/Bishkek',
  'LA': 'Asia/Vientiane',
  'LV': 'Europe/Riga',
  'LB': 'Asia/Beirut',
  'LS': 'Africa/Maseru',
  'LR': 'Africa/Monrovia',
  'LY': 'Africa/Tripoli',
  'LI': 'Europe/Vaduz',
  'LT': 'Europe/Vilnius',
  'LU': 'Europe/Luxembourg',
  'MO': 'Asia/Macau',
  'MG': 'Indian/Antananarivo',
  'MW': 'Africa/Blantyre',
  'MY': 'Asia/Kuala_Lumpur',
  'MV': 'Indian/Maldives',
  'ML': 'Africa/Bamako',
  'MT': 'Europe/Malta',
  'MH': 'Pacific/Majuro',
  'MQ': 'America/Martinique',
  'MR': 'Africa/Nouakchott',
  'MU': 'Indian/Mauritius',
  'YT': 'Indian/Mayotte',
  'MX-CT': 'America/Mexico_City',
  'MX-NW': 'America/Tijuana',
  'MX-PA': 'America/Mazatlan',
  'FM': 'Pacific/Chuuk',
  'MD': 'Europe/Chisinau',
  'MC': 'Europe/Monaco',
  'MN-E': 'Asia/Ulaanbaatar',
  'MN-W': 'Asia/Hovd',
  'ME': 'Europe/Podgorica',
  'MS': 'America/Montserrat',
  'MA': 'Africa/Casablanca',
  'MZ': 'Africa/Maputo',
  'MM': 'Asia/Yangon',
  'NA': 'Africa/Windhoek',
  'NR': 'Pacific/Nauru',
  'NP': 'Asia/Kathmandu',
  'NL': 'Europe/Amsterdam',
  'NC': 'Pacific/Noumea',
  'NZ': 'Pacific/Auckland',
  'NI': 'America/Managua',
  'NE': 'Africa/Niamey',
  'NG': 'Africa/Lagos',
  'NU': 'Pacific/Niue',
  'NF': 'Pacific/Norfolk',
  'KP': 'Asia/Pyongyang',
  'MK': 'Europe/Skopje',
  'MP': 'Pacific/Saipan',
  'NO': 'Europe/Oslo',
  'OM': 'Asia/Muscat',
  'PK': 'Asia/Karachi',
  'PW': 'Pacific/Palau',
  'PS': 'Asia/Hebron',
  'PA': 'America/Panama',
  'PG': 'Pacific/Port_Moresby',
  'PY': 'America/Asuncion',
  'PE': 'America/Lima',
  'PH': 'Asia/Manila',
  'PN': 'Pacific/Pitcairn',
  'PL': 'Europe/Warsaw',
  'PT': 'Europe/Lisbon',
  'PR': 'America/Puerto_Rico',
  'QA': 'Asia/Qatar',
  'CG': 'Africa/Brazzaville',
  'RE': 'Indian/Reunion',
  'RO': 'Europe/Bucharest',
  'RU-IRK': 'Asia/Irkutsk',
  'RU-KAL': 'Europe/Kaliningrad',
  'RU-KAM': 'Asia/Kamchatka',
  'RU-MSK': 'Europe/Moscow',
  'RU-VLA': 'Asia/Vladivostok',
  'RU-EKB': 'Asia/Yekaterinburg',
  'RW': 'Africa/Kigali',
  'AS': 'Pacific/Pago_Pago',
  'WS': 'Pacific/Apia',
  'SM': 'Europe/San_Marino',
  'ST': 'Africa/Sao_Tome',
  'SA': 'Asia/Riyadh',
  'SN': 'Africa/Dakar',
  'RS': 'Europe/Belgrade',
  'SC': 'Indian/Mahe',
  'SL': 'Africa/Freetown',
  'SG': 'Asia/Singapore',
  'SK': 'Europe/Bratislava',
  'SI': 'Europe/Ljubljana',
  'SB': 'Pacific/Guadalcanal',
  'SO': 'Africa/Mogadishu',
  'ZA': 'Africa/Johannesburg',
  'GS': 'Atlantic/South_Georgia',
  'KR': 'Asia/Seoul',
  'SS': 'Africa/Juba',
  'ES': 'Europe/Madrid',
  'LK': 'Asia/Colombo',
  'BL': 'America/St_Barthelemy',
  'SH': 'Atlantic/St_Helena',
  'KN': 'America/St_Kitts',
  'LC': 'America/St_Lucia',
  'SX': 'America/Lower_Princes',
  'MF': 'America/Marigot',
  'PM': 'America/Miquelon',
  'VC': 'America/St_Vincent',
  'SD': 'Africa/Khartoum',
  'SR': 'America/Paramaribo',
  'SJ': 'Arctic/Longyearbyen',
  'SE': 'Europe/Stockholm',
  'CH': 'Europe/Zurich',
  'SY': 'Asia/Damascus',
  'TW': 'Asia/Taipei',
  'TJ': 'Asia/Dushanbe',
  'TZ': 'Africa/Dar_es_Salaam',
  'TH': 'Asia/Bangkok',
  'TG': 'Africa/Lome',
  'TK': 'Pacific/Fakaofo',
  'TO': 'Pacific/Tongatapu',
  'TT': 'America/Port_of_Spain',
  'TN': 'Africa/Tunis',
  'TR': 'Europe/Istanbul',
  'TM': 'Asia/Ashgabat',
  'TC': 'America/Grand_Turk',
  'TV': 'Pacific/Funafuti',
  'VI': 'America/St_Thomas',
  'UG': 'Africa/Kampala',
  'UA': 'Europe/Kyiv',
  'AE': 'Asia/Dubai',
  'GB': 'Europe/London',
  'US-AK': 'America/Anchorage',
  'US-C': 'America/Chicago',
  'US-E': 'America/New_York',
  'US-HI': 'Pacific/Honolulu',
  'US-M': 'America/Denver',
  'US-P': 'America/Los_Angeles',
  'UY': 'America/Montevideo',
  'UM': 'Pacific/Midway',
  'UZ': 'Asia/Tashkent',
  'VU': 'Pacific/Efate',
  'VA': 'Europe/Vatican',
  'VE': 'America/Caracas',
  'VN': 'Asia/Ho_Chi_Minh',
  'WF': 'Pacific/Wallis',
  'EH': 'Africa/El_Aaiun',
  'YE': 'Asia/Aden',
  'ZM': 'Africa/Lusaka',
  'ZW': 'Africa/Harare',
};

export function getCountryByCode(code) {
  return COUNTRIES.find(c => c.code === code);
}

export function getCountryTimeZoneByCode(code) {
  return LEGACY_COUNTRY_TIMEZONES[code];
}
